// moppe's renderer over NHAL. A frame records, in the game's order: the
// scene (terrain, sky, draw lists and meshes) into a jittered RGBA16F
// colour, RG16F motion, and reversed-Z depth at the scene's scale; the
// temporal resolve into a history at the drawable's size; then the tonemap
// and the HUD into the drawable. Water, the forest's mesh-shader organs,
// undergrowth, dust, shadows, and the post effects are not drawn yet.
#include <moppe/nhal/renderer/nhal_renderer.hh>

#include <moppe/render/draw.hh>
#include <moppe/render/slug.hh>
#include <moppe/render/text.hh>
#include <moppe/render/texture_pixels.hh>
#include <moppe/render/types.hh>

// Generated by luv-shaderc from shaders/world.lisp.
#include <exposure.hh>
#include <forest.hh>
#include <forest_cull.hh>
#include <forest_shadow.hh>
#include <hud.hh>
#include <present.hh>
#include <resolve.hh>
#include <sky.hh>
#include <slug_text.hh>
#include <terrain.hh>
#include <terrain_shadow.hh>
#include <uber.hh>

#include <algorithm>
#include <array>
#include <bit>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <map>
#include <string>
#include <unordered_map>
#include <vector>

namespace moppe::nhal {
  namespace {
    using render::ChunkDraw;
    using render::DrawList;
    using render::DrawState;
    using render::FrameParams;

    using FrameBlock = shaders::terrain::Frame;
    static_assert (sizeof (FrameBlock) == sizeof (shaders::uber::Frame));
    static_assert (sizeof (FrameBlock) == sizeof (shaders::sky::Frame));
    static_assert (sizeof (FrameBlock) == sizeof (shaders::resolve::Frame));

    // The terrain's chunk levels, as the game's culling chooses them: a
    // step of source samples per rendered cell and vertices per chunk row.
    constexpr int chunk_cells = render::terrain_chunk_cells;
    constexpr int lod_count = int (render::TerrainLod::Count);
    constexpr float lod_step[lod_count] = { 0.25f, 1.0f, 2.0f, 4.0f, 8.0f };
    constexpr int lod_verts[lod_count] = { chunk_cells * 4 + 1, chunk_cells + 1,
                                           chunk_cells / 2 + 1,
                                           chunk_cells / 4 + 1,
                                           chunk_cells / 8 + 1 };

    // The trunk forest's (species, tier) classes, as forest_trunks.metal
    // numbers them: six detail tiers of birch, then six of spruce. A class's
    // topology -- facets, masses, and which vertices each triangle joins --
    // is a function of the two alone; world.lisp's forest-vertex places the
    // vertices in the same numbering.
    constexpr std::uint32_t forest_tiers = 6;
    constexpr std::uint32_t shadow_size = 2048;
    constexpr std::uint32_t forest_classes = 2 * forest_tiers;

    struct TreeTopology {
      std::uint32_t sides, crown_sides, masses;
      bool conifer, branches;

      TreeTopology (bool conifer_, std::uint32_t tier)
        : sides (tier >= 5 ? 10u : tier >= 2 ? 7u : 5u),
          crown_sides (sides == 10 ? 9u : sides),
          masses (conifer_ ? (tier >= 4 ? 5u : tier >= 1 ? 4u : 3u)
                           : (tier >= 4 ? 10u : tier >= 1 ? 7u : 4u)),
          conifer (conifer_), branches (!conifer_ && tier >= 3) {}

      std::uint32_t mass_vertices () const {
        return conifer ? crown_sides + 2 : 8 + (branches ? 6 : 0);
      }
      std::uint32_t mass_primitives () const {
        return conifer ? 2 * crown_sides : 12 + (branches ? 6 : 0);
      }

      void triangles (std::vector<std::uint16_t>& out) const {
        auto add = [&] (std::uint32_t a, std::uint32_t b, std::uint32_t c) {
          out.insert (out.end (), { std::uint16_t (a), std::uint16_t (b),
                                    std::uint16_t (c) });
        };
        // Three bands of quads between the trunk's four rings.
        for (std::uint32_t p = 0; p < sides * 6; ++p) {
          const std::uint32_t band = p / (2 * sides);
          const std::uint32_t quad = (p / 2) % sides;
          const std::uint32_t next = (quad + 1) % sides;
          const std::uint32_t a = band * sides + quad, b = band * sides + next;
          const std::uint32_t c = a + sides, d = b + sides;
          add ((p & 1) ? b : a, (p & 1) ? d : b, c);
        }
        for (std::uint32_t mass = 0; mass < masses; ++mass) {
          const std::uint32_t first = sides * 4 + mass * mass_vertices ();
          const std::uint32_t n = crown_sides;
          for (std::uint32_t p = 0; p < mass_primitives (); ++p) {
            if (conifer) {
              // A cone: its ring to the apex, then to the closing centre.
              const std::uint32_t side = p % n;
              add (first + side, first + (side + 1) % n,
                   first + (p < n ? n : n + 1));
            } else if (p < 12) {
              // A clump: six faces about its top tip, six about its bottom.
              const std::uint32_t k = p % 6;
              const std::uint32_t e0 = first + 2 + k;
              const std::uint32_t e1 = first + 2 + (k + 1) % 6;
              add (p < 6 ? first : first + 1, p < 6 ? e0 : e1,
                   p < 6 ? e1 : e0);
            } else {
              // Its branch, a three-sided prism.
              const std::uint32_t q = p - 12, k = q / 2;
              const std::uint32_t a = first + 8 + k;
              const std::uint32_t b = first + 8 + (k + 1) % 3;
              add ((q & 1) ? b : a, (q & 1) ? b + 3 : b, a + 3);
            }
          }
        }
      }
    };

    int patch_verts (int lod) {
      return (lod_verts[lod] - 1) * render::terrain_patch_cells / chunk_cells
             + 1;
    }

    std::array<float, 16> matrix (const Mat4& m) {
      std::array<float, 16> out;
      for (int i = 0; i < 16; ++i)
        out[i] = m.element (i);
      return out;
    }

    std::array<float, 4> lanes (const Vec3& v, float w = 0) {
      return { v[0], v[1], v[2], w };
    }

    std::array<float, 4> linear (DisplayColor c, float w = 0) {
      auto lin = [] (float x) { return std::pow (std::max (x, 0.0f), 2.2f); };
      return { lin (c.red), lin (c.green), lin (c.blue), w };
    }

    float halton (std::uint32_t index, std::uint32_t base) {
      float fraction = 1, result = 0;
      while (index > 0) {
        fraction /= float (base);
        result += fraction * float (index % base);
        index /= base;
      }
      return result;
    }

    // -- screenshots: a small, uncompressed PNG ---------------------------

    std::uint32_t crc (const std::uint8_t* data, std::size_t size,
                       std::uint32_t c = 0xffffffffu) {
      static std::uint32_t table[256];
      if (!table[1])
        for (std::uint32_t n = 0; n < 256; ++n) {
          std::uint32_t v = n;
          for (int k = 0; k < 8; ++k)
            v = v & 1 ? 0xedb88320u ^ (v >> 1) : v >> 1;
          table[n] = v;
        }
      for (std::size_t i = 0; i < size; ++i)
        c = table[(c ^ data[i]) & 255] ^ (c >> 8);
      return c;
    }

    void write_png (const std::string& path, std::uint32_t width,
                    std::uint32_t height,
                    const std::vector<std::uint8_t>& rgb) {
      std::vector<std::uint8_t> raw;
      raw.reserve ((width * 3 + 1) * height);
      for (std::uint32_t y = 0; y < height; ++y) {
        raw.push_back (0);
        raw.insert (raw.end (), rgb.begin () + std::size_t (y) * width * 3,
                    rgb.begin () + std::size_t (y + 1) * width * 3);
      }
      // zlib with stored deflate blocks.
      std::vector<std::uint8_t> z { 0x78, 0x01 };
      std::uint32_t a = 1, b = 0;
      for (std::size_t at = 0; at < raw.size ();) {
        const std::size_t n = std::min<std::size_t> (65535, raw.size () - at);
        z.push_back (at + n == raw.size () ? 1 : 0);
        z.push_back (n & 255);
        z.push_back (n >> 8);
        z.push_back (~n & 255);
        z.push_back ((~n >> 8) & 255);
        z.insert (z.end (), raw.begin () + at, raw.begin () + at + n);
        for (std::size_t i = at; i < at + n; ++i) {
          a = (a + raw[i]) % 65521;
          b = (b + a) % 65521;
        }
        at += n;
      }
      const std::uint32_t adler = (b << 16) | a;
      for (int s = 24; s >= 0; s -= 8)
        z.push_back ((adler >> s) & 255);

      FILE* file = std::fopen (path.c_str (), "wb");
      if (!file)
        return;
      auto u32 = [] (std::vector<std::uint8_t>& v, std::uint32_t x) {
        for (int s = 24; s >= 0; s -= 8)
          v.push_back ((x >> s) & 255);
      };
      auto chunk = [&] (const char* type, const std::vector<std::uint8_t>& d) {
        std::vector<std::uint8_t> out;
        u32 (out, std::uint32_t (d.size ()));
        out.insert (out.end (), type, type + 4);
        out.insert (out.end (), d.begin (), d.end ());
        u32 (out, ~crc (out.data () + 4, out.size () - 4));
        std::fwrite (out.data (), 1, out.size (), file);
      };
      const std::uint8_t signature[8] = { 137, 80, 78, 71, 13, 10, 26, 10 };
      std::fwrite (signature, 1, 8, file);
      std::vector<std::uint8_t> header;
      u32 (header, width);
      u32 (header, height);
      header.insert (header.end (), { 8, 2, 0, 0, 0 });
      chunk ("IHDR", header);
      chunk ("IDAT", z);
      chunk ("IEND", {});
      std::fclose (file);
    }

    float half_to_float (std::uint16_t h) {
      const std::uint32_t e = (h >> 10) & 31, m = h & 1023;
      const float v = e == 0 ? std::ldexp (float (m), -24)
                      : e == 31 ? 65504.0f
                                : std::ldexp (float (m | 1024), int (e) - 25);
      return (h >> 15) ? -v : v;
    }

    // -- resources the game holds -----------------------------------------

    struct NhalTexture final : render::Texture {
      Device* device = nullptr;
      nhal::Texture handle;
      ~NhalTexture () override { device->destroy (handle); }
    };

    struct NhalMesh final : render::Mesh {
      Device* device = nullptr;
      Buffer vertices;
      std::vector<DrawList::Run> runs;
      ~NhalMesh () override {
        if (vertices)
          device->destroy (vertices);
      }
    };

    struct NhalGlyphSet final : render::GlyphSet {
      Device* device = nullptr;
      Buffer curves, bands;
      ~NhalGlyphSet () override {
        device->destroy (curves);
        device->destroy (bands);
      }
    };

    // Owned copies of a program's stage code, which pipelines made on
    // demand need after construction.
    struct ProgramCode {
      std::string msl[2];
      std::vector<unsigned char> dxil[2];

      void keep (const StageCode (&stages)[2]) {
        for (int i = 0; i < 2; ++i) {
          msl[i] = std::string (stages[i].msl);
          dxil[i].assign (stages[i].dxil.begin (), stages[i].dxil.end ());
        }
      }
      StageCode stage (int i) const { return { msl[i], dxil[i] }; }
    };

    class NhalRenderer final : public render::Renderer {
    public:
      NhalRenderer (std::unique_ptr<Device> device,
                    const WorldShaders& shaders, float scale)
        : m_device (std::move (device)), m_scale (scale) {
        m_terrain_code.keep (shaders.terrain);
        m_sky_code.keep (shaders.sky);
        m_uber_code.keep (shaders.uber);
        m_hud_code.keep (shaders.hud);
        m_resolve_code.keep (shaders.resolve);
        m_present_code.keep (shaders.present);
        m_forest_code.keep (shaders.forest);
        m_terrain_shadow_code.keep (shaders.terrain_shadow);
        m_forest_shadow_code.keep (shaders.forest_shadow);
        m_forest_cull_code = std::string (shaders.forest_cull.msl);
        m_forest_cull_dxil.assign (shaders.forest_cull.dxil.begin (),
                                   shaders.forest_cull.dxil.end ());
        m_exposure_code = std::string (shaders.exposure.msl);
        m_exposure_dxil.assign (shaders.exposure.dxil.begin (),
                                shaders.exposure.dxil.end ());
        m_slug_text_code.keep (shaders.slug_text);
        make_pipelines ();
        const float neutral = 1.0f;
        m_exposure_value = m_device->create_buffer (
          { .size = 4, .usage = buffer_storage_write, .label = "exposure" },
          std::as_bytes (std::span (&neutral, 1)));
        const std::uint8_t white[4] = { 255, 255, 255, 255 };
        m_white = m_device->create_texture ({ 1, 1, Format::rgba8_unorm,
                                              usage_sampled, 1, "white" });
        m_device->write_texture (m_white, std::as_bytes (std::span (white)));
        std::cerr << "moppe: NHAL renderer on " << m_device->info ().backend
                  << " (" << m_device->info ().adapter << ")" << std::endl;
      }

      ~NhalRenderer () override {
        m_device->wait_idle ();
      }

      // -- resources ------------------------------------------------------

      render::TexturePtr create_texture (const render::TextureDesc& desc,
                                         const void* pixels) override {
        auto texture = std::make_shared<NhalTexture> ();
        texture->device = m_device.get ();
        texture->width = desc.width;
        texture->height = desc.height;
        texture->handle = m_device->create_texture (
          { std::uint32_t (desc.width), std::uint32_t (desc.height),
            Format::rgba8_unorm_srgb, usage_sampled, 1, "game texture" });
        const std::size_t texels = std::size_t (desc.width) * desc.height;
        std::vector<std::uint8_t> rgba (texels * 4, 255);
        const auto* source = static_cast<const std::uint8_t*> (pixels);
        if (source && desc.format == render::TextureFormat::RGB8) {
          for (std::size_t i = 0; i < texels; ++i)
            std::memcpy (&rgba[i * 4], &source[i * 3], 3);
        } else if (source) {
          std::memcpy (rgba.data (), source, rgba.size ());
        }
        m_device->write_texture (texture->handle,
                                 std::as_bytes (std::span (rgba)));
        return texture;
      }

      render::MeshPtr create_mesh (const DrawList& recorded) override {
        auto mesh = std::make_shared<NhalMesh> ();
        mesh->device = m_device.get ();
        const auto& vertices = recorded.vertices ();
        if (!vertices.empty ())
          mesh->vertices = m_device->create_buffer (
            { .size = vertices.size () * sizeof (render::Vertex),
              .label = "mesh" },
            std::as_bytes (std::span (vertices)));
        mesh->runs = recorded.runs ();
        return mesh;
      }

      render::GlyphSetPtr
      create_glyph_set (const render::SlugGlyphData& data) override {
        if (data.curves.empty () || data.bands.empty ())
          return nullptr;
        auto set = std::make_shared<NhalGlyphSet> ();
        set->device = m_device.get ();
        set->curves = m_device->create_buffer (
          { .size = data.curves.size () * sizeof (render::SlugCurveTexel),
            .label = "slug curves" },
          std::as_bytes (std::span (data.curves)));
        set->bands = m_device->create_buffer (
          { .size = data.bands.size () * sizeof (std::uint32_t),
            .label = "slug bands" },
          std::as_bytes (std::span (data.bands)));
        return set;
      }

      // -- world setup ----------------------------------------------------

      void set_terrain (const render::TerrainParams& params,
                        std::span<const terrain::SurfaceElevation> heights,
                        std::span<const terrain::TerrainNormal> normals)
        override {
        m_terrain_params = params;
        const std::uint32_t w = params.width, h = params.height;
        for (Texture* t : { &m_heights, &m_normals })
          if (*t)
            m_device->destroy (*t);
        m_heights = m_device->create_texture (
          { w, h, Format::r32_float, usage_sampled, 1, "terrain heights" });
        static_assert (sizeof (terrain::SurfaceElevation) == sizeof (float));
        m_device->write_texture (m_heights, std::as_bytes (heights));
        // Normals: x and z as RG16 snorm; the shader rebuilds y.
        m_normals = m_device->create_texture (
          { w, h, Format::rg16_snorm, usage_sampled, 1, "terrain normals" });
        std::vector<std::int16_t> packed (normals.size () * 2);
        for (std::size_t i = 0; i < normals.size (); ++i) {
          const Vec3 n = normals[i].numerical_value_in (mp_units::one);
          packed[i * 2] = std::int16_t (std::clamp (n[0], -1.0f, 1.0f)
                                        * 32767.0f);
          packed[i * 2 + 1] = std::int16_t (std::clamp (n[2], -1.0f, 1.0f)
                                            * 32767.0f);
        }
        m_device->write_texture (m_normals,
                                 std::as_bytes (std::span (packed)));

        // Strip index templates per level, whole chunks and patches, with
        // the all-ones restart between rows.
        if (!m_chunk_indices[0]) {
          auto strips = [&] (int verts, const char* label) {
            std::vector<std::uint32_t> indices;
            for (int row = 0; row + 1 < verts; ++row) {
              for (int x = 0; x < verts; ++x) {
                indices.push_back (std::uint32_t (row * verts + x));
                indices.push_back (std::uint32_t ((row + 1) * verts + x));
              }
              indices.push_back (0xffffffffu);
            }
            const Buffer buffer = m_device->create_buffer (
              { .size = indices.size () * 4, .label = label },
              std::as_bytes (std::span (indices)));
            return std::pair (buffer, std::uint32_t (indices.size ()));
          };
          for (int lod = 0; lod < lod_count; ++lod) {
            std::tie (m_chunk_indices[lod], m_chunk_index_count[lod]) =
              strips (lod_verts[lod], "terrain chunk strips");
            std::tie (m_patch_indices[lod], m_patch_index_count[lod]) =
              strips (patch_verts (lod), "terrain patch strips");
          }
        }
        m_have_terrain = true;
      }

      void set_terrain_topology_overlay (bool) override {}

      void set_terrain_textures (render::TexturePtr grass,
                                 render::TexturePtr dirt,
                                 render::TexturePtr rock,
                                 render::TexturePtr snow) override {
        m_grass = grass;
        m_dirt = dirt;
        m_rock = rock;
        m_snow = snow;
      }

      void set_terrain_overlay (const render::TerrainOverlayParams&,
                                std::span<const float>) override {}
      void clear_terrain_overlay () override {}
      void render_terrain_shadow (const Mat4&, bool) override {}
      void set_ocean (const render::OceanSetup&,
                      const render::TexturePixels&) override {}

      void set_forest (const render::ForestSetup& setup,
                       std::span<const render::ForestInstance> instances)
        override {
        for (Buffer* b : { &m_trees, &m_tree_candidates, &m_tree_arguments,
                           &m_shadow_candidates, &m_shadow_arguments })
          if (*b)
            m_device->destroy (*b), *b = {};
        m_tree_count = std::uint32_t (instances.size ());
        if (instances.empty ())
          return;
        // Four rows a tree. The stand closure that decides where a crown
        // starts is approximated by the habitat's canopy cover for now.
        std::vector<std::array<float, 4>> rows;
        rows.reserve (instances.size () * 4);
        for (const render::ForestInstance& tree : instances) {
          const Vec3 root = position_value (tree.root);
          const Vec3 up = tree.ground_normal.numerical_value_in (mp_units::one);
          const float cover =
            tree.canopy_cover.numerical_value_in (mp_units::one);
          auto bits = [] (std::uint32_t u) { return std::bit_cast<float> (u); };
          rows.push_back ({ root[0], root[1], root[2],
                            tree.height.numerical_value_in (u::m) });
          rows.push_back ({ up[0], up[1], up[2],
                            tree.crown_radius.numerical_value_in (u::m) });
          rows.push_back ({ cover,
                            tree.moisture.numerical_value_in (mp_units::one),
                            cover,
                            tree.autumn.numerical_value_in (mp_units::one) });
          rows.push_back ({ bits (tree.seed),
                            bits (std::uint32_t (tree.species)),
                            bits (std::uint32_t (tree.age)), 0 });
        }
        m_trees = m_device->create_buffer (
          { .size = rows.size () * 16, .label = "forest records" },
          std::as_bytes (std::span (rows)));
        // Every class can hold every tree, so the cull never overflows.
        m_tree_candidates = m_device->create_buffer (
          { .size = std::uint64_t (forest_classes) * m_tree_count * 8,
            .usage = buffer_storage_write,
            .label = "forest candidates" });
        m_tree_arguments = m_device->create_buffer (
          { .size = forest_classes * sizeof (DrawIndexedIndirectArgs),
            .usage = buffer_storage_write | buffer_indirect,
            .label = "forest draws" });
        m_shadow_candidates = m_device->create_buffer (
          { .size = 2ull * m_tree_count * 8,
            .usage = buffer_storage_write,
            .label = "shadow tree candidates" });
        m_shadow_arguments = m_device->create_buffer (
          { .size = 2 * sizeof (DrawIndexedIndirectArgs),
            .usage = buffer_storage_write | buffer_indirect,
            .label = "shadow tree draws" });
        const Vec3 period = extent_value (setup.period);
        m_tree_period[0] = period[0];
        m_tree_period[1] = period[2];

        if (!m_tree_indices) {
          std::vector<std::uint16_t> indices;
          for (std::uint32_t c = 0; c < forest_classes; ++c) {
            m_tree_class_first[c] = std::uint32_t (indices.size ());
            TreeTopology (c >= forest_tiers, c % forest_tiers)
              .triangles (indices);
            m_tree_class_count[c] =
              std::uint32_t (indices.size ()) - m_tree_class_first[c];
          }
          m_tree_indices = m_device->create_buffer (
            { .size = indices.size () * 2, .label = "forest topology" },
            std::as_bytes (std::span (indices)));
        }
      }

      void set_terrain_materials (const render::TexturePixels& landscape,
                                  const render::TexturePixels& ground,
                                  bool) override {
        auto sheet = [&] (Texture& texture,
                          const render::TexturePixels& pixels,
                          const char* label) {
          if (texture)
            m_device->destroy (texture);
          texture = {};
          if (pixels.empty ()
              || pixels.format () != render::PixelFormat::rgba8unorm)
            return;
          texture = m_device->create_texture (
            { std::uint32_t (pixels.width ()), std::uint32_t (pixels.height ()),
              Format::rgba8_unorm, usage_sampled, 1, label });
          std::vector<std::byte> bytes (pixels.byte_size ());
          pixels.write_into (bytes.data ());
          m_device->write_texture (texture, bytes);
        };
        sheet (m_landscape, landscape, "landscape materials");
        sheet (m_ground, ground, "ground materials");
      }

      // -- a frame --------------------------------------------------------

      void offer_platform_drawable (void* drawable) override {
        m_device->offer_drawable (drawable);
      }

      bool begin_frame (const FrameParams& params) override {
        if (!m_device->begin_frame ())
          return false;
        if (m_width != m_device->surface_width ()
            || m_height != m_device->surface_height ())
          make_targets ();
        m_params = params;
        m_scene_open = m_resolved = m_presented = false;

        const Mat4 view_proj = params.proj * params.view;
        if (m_restart)
          m_previous_view_proj = view_proj, m_previous_time = params.time;
        const float tan_x = 1.0f / params.proj.at (0, 0);
        const float tan_y = 1.0f / params.proj.at (1, 1);
        const std::uint32_t phase = m_frame++ % 16 + 1;

        FrameBlock frame {};
        frame.view_proj = matrix (view_proj);
        frame.previous_view_proj = matrix (m_previous_view_proj);
        frame.camera_position = lanes (params.camera_pos, params.time);
        frame.sun_direction = lanes (params.sun_dir, params.cloud_cover);
        frame.sun_diffuse = linear (params.sun_diffuse);
        frame.sun_specular = linear (params.sun_specular);
        frame.ambient = linear (params.ambient);
        frame.fog_color = linear (params.clear_color, params.fog_scale);
        frame.relief = { m_terrain_params.sea_level,
                         m_terrain_params.land_relief, m_previous_time, 0 };
        frame.view_right = lanes (params.cam_right * tan_x);
        frame.view_up = lanes (params.cam_up * tan_y);
        frame.view_forward = lanes (params.cam_forward);
        frame.temporal = { float (m_scene_width), float (m_scene_height),
                           (halton (phase, 2) - 0.5f) * 2
                             / float (m_scene_width),
                           (halton (phase, 3) - 0.5f) * 2
                             / float (m_scene_height) };
        frame.temporal_blend = { m_restart ? 1.0f : 0.1f, 0, float (m_width),
                                 float (m_height) };
        frame.shadow = { 0, 1.0f / shadow_size, 0, 0 };
        m_frame_values = frame;
        upload_frame ();
        cull_trees (view_proj, params.camera_pos, float (m_scene_height),
                    false);

        m_previous_view_proj = view_proj;
        m_previous_time = params.time;
        m_restart = false;
        return true;
      }

      // The sun's shadow over the rider's neighbourhood: terrain chunks at
      // native detail and the trees, each species at its coarsest tier.
      void render_local_shadow (const render::LocalShadowParams& params)
        override {
        if (!m_have_terrain || m_scene_open || m_resolved)
          return;
        const Vec3 focus = position_value (params.focus);
        const Mat4& light = params.light_view_proj;
        const bool trees = params.include_forest && m_tree_count;
        if (trees)
          cull_trees (light, focus, 1.0f, true);

        RenderPassDesc pass;
        pass.label = "sun shadow";
        pass.depth = { m_shadow_map, Load::clear, Store::store, 1.0f };
        m_device->begin_render_pass (pass);
        shaders::terrain_shadow::Caster caster {};
        caster.light_view = matrix (light);
        caster.focus = lanes (focus, m_params.time);
        const Transient caster_block = m_device->allocate (sizeof caster);
        std::memcpy (caster_block.data, &caster, sizeof caster);

        m_device->set_pipeline (m_terrain_shadow);
        m_device->set_buffer (0, caster_block);
        m_device->set_uniforms (1, terrain_block ());
        m_device->set_texture (0, m_heights);
        const auto& t = m_terrain_params;
        const int chunks_x = t.width / chunk_cells;
        const int chunks_z = t.height / chunk_cells;
        const float chunk_width = chunk_cells * t.scale[0];
        const float chunk_depth = chunk_cells * t.scale[2];
        const float reach = params.radius.numerical_value_in (u::m);
        const float draw_reach =
          reach + 0.5f * std::hypot (chunk_width, chunk_depth);
        const int centre_x = int (std::floor (focus[0] / chunk_width));
        const int centre_z = int (std::floor (focus[2] / chunk_depth));
        const int reach_x = int (std::ceil (reach / chunk_width)) + 1;
        const int reach_z = int (std::ceil (reach / chunk_depth)) + 1;
        auto floor_div = [] (int v, int d) {
          return v / d - (v % d < 0 ? 1 : 0);
        };
        constexpr int native = int (render::TerrainLod::Native);
        for (int z = centre_z - reach_z; z <= centre_z + reach_z; ++z)
          for (int x = centre_x - reach_x; x <= centre_x + reach_x; ++x) {
            const float dx = (x + 0.5f) * chunk_width - focus[0];
            const float dz = (z + 0.5f) * chunk_depth - focus[2];
            if (dx * dx + dz * dz > draw_reach * draw_reach)
              continue;
            const int wrap_x = floor_div (x, chunks_x);
            const int wrap_z = floor_div (z, chunks_z);
            shaders::terrain_shadow::Chunk chunk {};
            chunk.placement = { float ((x - wrap_x * chunks_x) * chunk_cells),
                                float ((z - wrap_z * chunks_z) * chunk_cells),
                                lod_step[native], float (lod_verts[native]) };
            chunk.offset = { wrap_x * chunks_x * chunk_width, 0,
                             wrap_z * chunks_z * chunk_depth, 0 };
            m_device->set_uniforms (2, chunk);
            m_device->draw_indexed (m_chunk_indices[native],
                                    IndexType::uint32,
                                    m_chunk_index_count[native]);
          }

        if (trees) {
          m_device->set_pipeline (m_forest_shadow);
          m_device->set_buffer (0, caster_block);
          m_device->set_buffer (1, m_shadow_forest_block);
          m_device->set_buffer (3, m_trees);
          m_device->set_buffer (4, m_shadow_candidates);
          for (std::uint32_t species = 0; species < 2; ++species) {
            shaders::forest_shadow::Draw draw {};
            draw.class_ = { float (species * m_tree_count), 0, 0, 0 };
            m_device->set_uniforms (2, draw);
            m_device->draw_indexed_indirect (
              m_tree_indices, IndexType::uint16, m_shadow_arguments,
              species * sizeof (DrawIndexedIndirectArgs));
          }
        }
        m_device->end_render_pass ();

        m_frame_values.sun_view = matrix (light);
        m_frame_values.shadow = { m_terrain_params.shadow_strength,
                           1.0f / shadow_size, 0, 0 };
        upload_frame ();
      }

      void draw_terrain (const ChunkDraw* chunks, int count) override {
        if (!m_have_terrain || count <= 0)
          return;
        open_scene ();
        m_device->set_pipeline (m_terrain);
        m_device->set_buffer (0, m_frame_block);
        m_device->set_uniforms (1, terrain_block ());
        m_device->set_texture (0, m_heights);
        m_device->set_texture (1, m_normals);
        m_device->set_texture (2, texture_or_white (m_grass));
        m_device->set_texture (3, texture_or_white (m_dirt));
        m_device->set_texture (4, texture_or_white (m_rock));
        m_device->set_texture (5, texture_or_white (m_snow));
        m_device->set_texture (6, m_landscape ? m_landscape : m_white);
        m_device->set_texture (7, m_ground ? m_ground : m_white);
        m_device->set_texture (8, m_shadow_map);
        for (int i = 0; i < count; ++i) {
          const ChunkDraw& c = chunks[i];
          const int lod = std::clamp (int (c.lod), 0, lod_count - 1);
          const bool patch = c.cells == render::terrain_patch_cells;
          shaders::terrain::Chunk chunk {};
          chunk.placement = { float (c.x0), float (c.z0), lod_step[lod],
                              float (patch ? patch_verts (lod)
                                           : lod_verts[lod]) };
          chunk.morph = { c.morph_start, c.morph_end,
                          lod_step[std::min (lod + 1, lod_count - 1)], 0 };
          chunk.offset = { c.offset_x, 0, c.offset_z, 0 };
          m_device->set_uniforms (2, chunk);
          m_device->draw_indexed (
            patch ? m_patch_indices[lod] : m_chunk_indices[lod],
            IndexType::uint32,
            patch ? m_patch_index_count[lod] : m_chunk_index_count[lod]);
        }
      }

      void draw_forest () override {
        if (!m_tree_count)
          return;
        open_scene ();
        m_device->set_pipeline (m_forest);
        m_device->set_buffer (0, m_frame_block);
        m_device->set_buffer (1, m_forest_block);
        m_device->set_buffer (3, m_trees);
        m_device->set_buffer (4, m_tree_candidates);
        m_device->set_texture (8, m_shadow_map);
        for (std::uint32_t c = 0; c < forest_classes; ++c) {
          shaders::forest::Draw draw {};
          draw.class_ = { float (c * m_tree_count), 0, 0, 0 };
          m_device->set_uniforms (2, draw);
          m_device->draw_indexed_indirect (
            m_tree_indices, IndexType::uint16, m_tree_arguments,
            c * sizeof (DrawIndexedIndirectArgs));
        }
      }

      void draw_sky (const render::SkyParams&) override {
        open_scene ();
        m_device->set_pipeline (m_sky);
        m_device->set_buffer (0, m_frame_block);
        m_device->draw (3);
      }

      void draw_ocean (const render::OceanParams&) override {}
      void draw_waterfalls (const render::Mesh&, const Mat4&) override {}

      void draw_list (const DrawList& list, std::uint64_t) override {
        if (list.empty ())
          return;
        open_scene ();
        const Transient vertices =
          m_device->upload (std::span (list.vertices ()));
        draw_runs (vertices, Buffer {}, list.runs (), Mat4 {}, Mat4 {});
      }

      void draw_mesh (const render::Mesh& mesh, const Mat4& model,
                      std::uint64_t motion_id) override {
        const auto& m = static_cast<const NhalMesh&> (mesh);
        if (!m.vertices)
          return;
        open_scene ();
        Mat4 previous = model;
        if (motion_id) {
          if (auto found = m_previous_models.find (motion_id);
              found != m_previous_models.end ())
            previous = found->second;
          m_current_models[motion_id] = model;
        }
        draw_runs ({}, m.vertices, m.runs, model, previous);
      }

      void reconstruct_scene () override {
        if (m_resolved)
          return;
        open_scene ();
        m_device->end_render_pass ();
        m_scene_open = false;
        Texture& previous = m_history[m_frame % 2];
        Texture& next = m_history[(m_frame + 1) % 2];
        RenderPassDesc pass;
        pass.label = "temporal resolve";
        pass.color_count = 1;
        pass.colors[0] = { next, Load::discard, Store::store };
        m_device->begin_render_pass (pass);
        m_device->set_pipeline (m_resolve);
        m_device->set_buffer (0, m_frame_block);
        m_device->set_texture (0, m_scene_color);
        m_device->set_texture (1, m_scene_motion);
        m_device->set_texture (2, m_scene_depth);
        m_device->set_texture (3, previous);
        m_device->draw (3);
        m_device->end_render_pass ();
        m_image = next;
        m_resolved = true;

        if (m_params.auto_exposure) {
          m_device->begin_compute_pass ("exposure");
          m_device->set_pipeline (m_exposure);
          m_device->set_texture (0, m_image);
          m_device->set_buffer (1, m_exposure_value);
          m_device->dispatch (1);
          m_device->end_compute_pass ();
        }
      }

      void apply_underwater (float) override {}
      void apply_motion_blur (float) override {}
      void apply_scene_blur () override {}

      void draw_hud_text (const render::TextList& text) override {
        m_hud_text = text;
      }

      // The HUD's draw list, then its Slug text over it.
      void draw_hud (const DrawList& list) override {
        open_present ();
        shaders::hud::Hud hud {};
        hud.projection = matrix (Mat4::hud_ortho (width_pts (), height_pts ()));
        hud.output = { m_device->surface_format () == Format::rgba16_float
                         ? 1.0f
                         : 0.0f,
                       m_scale, 0, 0 };
        if (!list.empty ()) {
          m_device->set_pipeline (m_hud);
          m_device->set_uniforms (0, hud);
          m_device->set_buffer (
            1, m_device->upload (std::span (list.vertices ())));
          for (const DrawList::Run& run : list.runs ()) {
            if (!run.count)
              continue;
            m_device->set_texture (0, texture_or_white (run.texture));
            m_device->draw (run.count, 1, run.first);
          }
        }
        if (!m_hud_text.empty ()) {
          m_device->set_pipeline (m_slug_text);
          m_device->set_uniforms (0, hud);
          const auto& quads = m_hud_text.quads ();
          for (const render::TextList::Run& run : m_hud_text.runs ()) {
            const auto* glyphs =
              static_cast<const NhalGlyphSet*> (run.glyphs.get ());
            if (!glyphs || !run.count)
              continue;
            // Each run's quads in a slice of their own: Direct3D's instance
            // index does not count from a draw's first instance.
            m_device->set_buffer (
              1, m_device->upload (std::span (quads).subspan (run.first,
                                                              run.count)));
            m_device->set_buffer (2, glyphs->curves);
            m_device->set_buffer (3, glyphs->bands);
            m_device->draw (6, run.count);
          }
          m_hud_text.clear ();
        }
      }

      void request_screenshot (const std::string& path) override {
        m_screenshot = path;
      }

      void end_frame () override {
        open_present ();
        m_device->end_render_pass ();
        if (!m_screenshot.empty ()) {
          m_device->capture_frame ([path = m_screenshot] (
                                     const Capture& capture) {
            const Format format = capture.format;
            std::vector<std::uint8_t> rgb (std::size_t (capture.width)
                                           * capture.height * 3);
            for (std::uint32_t y = 0; y < capture.height; ++y)
              for (std::uint32_t x = 0; x < capture.width; ++x) {
                const std::byte* p = capture.pixels.data ()
                                     + std::size_t (y) * capture.row_bytes
                                     + std::size_t (x)
                                         * bytes_per_pixel (format);
                std::uint8_t* out = &rgb[(std::size_t (y) * capture.width + x)
                                         * 3];
                if (format == Format::rgba16_float) {
                  for (int c = 0; c < 3; ++c) {
                    std::uint16_t h;
                    std::memcpy (&h, p + c * 2, 2);
                    const float v = std::clamp (half_to_float (h), 0.0f, 1.0f);
                    out[c] = std::uint8_t (std::pow (v, 1 / 2.2f) * 255 + 0.5f);
                  }
                } else {
                  const bool bgra = format == Format::bgra8_unorm;
                  out[0] = std::uint8_t (p[bgra ? 2 : 0]);
                  out[1] = std::uint8_t (p[1]);
                  out[2] = std::uint8_t (p[bgra ? 0 : 2]);
                }
              }
            write_png (path, capture.width, capture.height, rgb);
            std::cerr << "moppe: wrote " << path << std::endl;
          });
          m_screenshot.clear ();
          // Hosts may quit straight after the frame they asked to capture,
          // so the readback completes here rather than next frame.
          m_device->end_frame ();
          m_device->wait_idle ();
        } else {
          m_device->end_frame ();
        }
        m_previous_models.swap (m_current_models);
        m_current_models.clear ();
        report_timings ();
      }

      // MOPPE_NHAL_TIMINGS=1 prints each pass's GPU time every two
      // seconds, averaged over the frames since the last report.
      void report_timings () {
        static const bool wanted = [] {
          const char* v = std::getenv ("MOPPE_NHAL_TIMINGS");
          return v && *v && *v != '0';
        }();
        if (!wanted)
          return;
        for (const PassTiming& pass : m_device->pass_timings ())
          m_timing_sums[pass.label] += pass.milliseconds;
        if (++m_timing_frames < 120)
          return;
        double total = 0;
        std::cerr << "moppe: NHAL GPU ms:";
        for (const auto& [label, sum] : m_timing_sums) {
          std::cerr << ' ' << label << '=' << sum / m_timing_frames;
          total += sum / m_timing_frames;
        }
        std::cerr << " total=" << total << std::endl;
        m_timing_sums.clear ();
        m_timing_frames = 0;
      }

      void reset_temporal_state () override { m_restart = true; }

      int width_pts () const override {
        return int (float (m_device->surface_width ()) / m_scale);
      }
      int height_pts () const override {
        return int (float (m_device->surface_height ()) / m_scale);
      }
      float scale_factor () const override { return m_scale; }

    private:
      void make_pipelines () {
        RenderPipelineDesc scene;
        scene.color_formats[0] = Format::rgba16_float;
        scene.color_formats[1] = Format::rg16_float;
        scene.color_count = 2;
        scene.depth_format = Format::d32_float;
        scene.cull = Cull::back;

        RenderPipelineDesc terrain = scene;
        terrain.program = &shaders::terrain::program;
        terrain.vertex = m_terrain_code.stage (0);
        terrain.fragment = m_terrain_code.stage (1);
        terrain.topology = Topology::triangle_strip;
        m_terrain = m_device->create_render_pipeline (terrain);

        RenderPipelineDesc sky = scene;
        sky.program = &shaders::sky::program;
        sky.vertex = m_sky_code.stage (0);
        sky.fragment = m_sky_code.stage (1);
        sky.cull = Cull::none;
        sky.depth_write = false;
        m_sky = m_device->create_render_pipeline (sky);

        RenderPipelineDesc forest = scene;
        forest.program = &shaders::forest::program;
        forest.vertex = m_forest_code.stage (0);
        forest.fragment = m_forest_code.stage (1);
        forest.cull = Cull::none;
        forest.label = "forest";
        m_forest = m_device->create_render_pipeline (forest);
        m_exposure = m_device->create_compute_pipeline (
          { &shaders::exposure::program,
            { m_exposure_code, m_exposure_dxil }, "exposure" });
        m_forest_cull = m_device->create_compute_pipeline (
          { &shaders::forest_cull::program,
            { m_forest_cull_code, m_forest_cull_dxil }, "forest culling" });

        RenderPipelineDesc caster;
        caster.color_count = 0;
        caster.depth_format = Format::d32_float;
        caster.depth_compare = CompareOp::less_equal;
        caster.depth_bias = 2.0f;
        caster.slope_scaled_depth_bias = 2.0f;
        RenderPipelineDesc terrain_caster = caster;
        terrain_caster.program = &shaders::terrain_shadow::program;
        terrain_caster.vertex = m_terrain_shadow_code.stage (0);
        terrain_caster.topology = Topology::triangle_strip;
        terrain_caster.label = "terrain shadow";
        m_terrain_shadow = m_device->create_render_pipeline (terrain_caster);
        RenderPipelineDesc tree_caster = caster;
        tree_caster.program = &shaders::forest_shadow::program;
        tree_caster.vertex = m_forest_shadow_code.stage (0);
        tree_caster.label = "forest shadow";
        m_forest_shadow = m_device->create_render_pipeline (tree_caster);
        m_shadow_map = m_device->create_texture (
          { shadow_size, shadow_size, Format::d32_float,
            usage_depth | usage_sampled, 1, "sun shadow" });

        RenderPipelineDesc resolve;
        resolve.program = &shaders::resolve::program;
        resolve.vertex = m_resolve_code.stage (0);
        resolve.fragment = m_resolve_code.stage (1);
        resolve.color_formats[0] = Format::rgba16_float;
        m_resolve = m_device->create_render_pipeline (resolve);

        RenderPipelineDesc present;
        present.program = &shaders::present::program;
        present.vertex = m_present_code.stage (0);
        present.fragment = m_present_code.stage (1);
        present.color_formats[0] = m_device->surface_format ();
        m_present = m_device->create_render_pipeline (present);

        RenderPipelineDesc hud = present;
        hud.program = &shaders::hud::program;
        hud.vertex = m_hud_code.stage (0);
        hud.fragment = m_hud_code.stage (1);
        hud.blend[0] = Blend::alpha;
        m_hud = m_device->create_render_pipeline (hud);

        RenderPipelineDesc text = hud;
        text.program = &shaders::slug_text::program;
        text.vertex = m_slug_text_code.stage (0);
        text.fragment = m_slug_text_code.stage (1);
        m_slug_text = m_device->create_render_pipeline (text);
      }

      void upload_frame () {
        m_frame_block = m_device->allocate (sizeof m_frame_values);
        std::memcpy (m_frame_block.data, &m_frame_values,
                     sizeof m_frame_values);
      }

      shaders::terrain::Terrain terrain_block () const {
        shaders::terrain::Terrain terrain {};
        const auto& p = m_terrain_params;
        terrain.scale = { p.scale[0], p.scale[1], p.scale[2], p.tex_scale };
        terrain.fields = { m_landscape && m_ground ? 1.0f : 0.0f, 0, 0, 0 };
        terrain.size = { float (p.width), float (p.height), 0, 0 };
        return terrain;
      }

      // Every tree tested against a view, appended to its class's list and
      // counted into the class's indirect draw: twelve classes for the
      // camera, two (a species each, coarsest tier) for the sun's shadow.
      // Runs outside render passes, which compute passes may not overlap.
      void cull_trees (const Mat4& view, const Vec3& eye, float height,
                       bool shadow) {
        if (!m_tree_count)
          return;
        auto row = [&] (int r) {
          return std::sqrt (view.element (r) * view.element (r)
                            + view.element (4 + r) * view.element (4 + r)
                            + view.element (8 + r) * view.element (8 + r));
        };
        shaders::forest_cull::Forest forest {};
        forest.view = matrix (view);
        forest.eye = lanes (eye);
        forest.world = { m_tree_period[0], m_tree_period[1],
                         float (m_tree_count), float (m_tree_count) };
        forest.cull = { row (0), row (1), row (3), height };
        forest.mode = { shadow ? 1.0f : 0.0f, 0, 0, 0 };
        Transient& block = shadow ? m_shadow_forest_block : m_forest_block;
        block = m_device->allocate (sizeof forest);
        std::memcpy (block.data, &forest, sizeof forest);

        std::array<DrawIndexedIndirectArgs, forest_classes> reset {};
        for (std::uint32_t c = 0; c < forest_classes; ++c) {
          // The shadow's two classes are each species' tier 0.
          const std::uint32_t topology = shadow ? c * forest_tiers : c;
          if (topology < forest_classes)
            reset[c] = { m_tree_class_count[topology], 0,
                         m_tree_class_first[topology], 0, 0 };
        }
        const Buffer arguments =
          shadow ? m_shadow_arguments : m_tree_arguments;
        m_device->copy_to_buffer (
          arguments, 0,
          m_device->upload (std::span<const DrawIndexedIndirectArgs> (
            reset.data (), shadow ? 2 : forest_classes)));
        m_device->begin_compute_pass (shadow ? "shadow tree culling"
                                             : "forest culling");
        m_device->set_pipeline (m_forest_cull);
        m_device->set_buffer (1, block);
        m_device->set_buffer (2, m_trees);
        m_device->set_buffer (3,
                              shadow ? m_shadow_candidates : m_tree_candidates);
        m_device->set_buffer (4, arguments);
        m_device->dispatch ((m_tree_count + 63) / 64);
        m_device->end_compute_pass ();
      }

      // The draw-list pipeline for a run's fixed-function state.
      Pipeline uber (const DrawState& state) {
        const int key = (state.blend ? 1 : 0) | (state.additive ? 2 : 0)
                        | (state.depth_test ? 4 : 0)
                        | (state.depth_write ? 8 : 0) | (state.cull ? 16 : 0);
        Pipeline& pipeline = m_uber[key];
        if (pipeline)
          return pipeline;
        RenderPipelineDesc desc;
        desc.program = &shaders::uber::program;
        desc.vertex = m_uber_code.stage (0);
        desc.fragment = m_uber_code.stage (1);
        desc.color_formats[0] = Format::rgba16_float;
        desc.color_formats[1] = Format::rg16_float;
        desc.color_count = 2;
        desc.blend[0] = state.additive ? Blend::additive
                        : state.blend  ? Blend::alpha
                                       : Blend::none;
        desc.depth_format = Format::d32_float;
        desc.depth_compare = state.depth_test ? CompareOp::greater_equal
                                              : CompareOp::always;
        desc.depth_write = state.depth_write;
        desc.cull = state.cull ? Cull::back : Cull::none;
        pipeline = m_device->create_render_pipeline (desc);
        return pipeline;
      }

      void draw_runs (const Transient& streamed, Buffer baked,
                      const std::vector<DrawList::Run>& runs,
                      const Mat4& model, const Mat4& previous) {
        shaders::uber::Draw draw {};
        draw.model = matrix (model);
        draw.previous_model = matrix (previous);
        // The normal matrix: the inverse transpose of the model's 3x3.
        float m[3][3];
        for (int c = 0; c < 3; ++c)
          for (int r = 0; r < 3; ++r)
            m[c][r] = model.at (c, r);
        const float det = m[0][0] * (m[1][1] * m[2][2] - m[2][1] * m[1][2])
                          - m[1][0] * (m[0][1] * m[2][2] - m[2][1] * m[0][2])
                          + m[2][0] * (m[0][1] * m[1][2] - m[1][1] * m[0][2]);
        const float inv = std::abs (det) > 1e-12f ? 1.0f / det : 1.0f;
        auto cof = [&] (int c, int r) {
          const int c1 = (c + 1) % 3, c2 = (c + 2) % 3;
          const int r1 = (r + 1) % 3, r2 = (r + 2) % 3;
          return (m[c1][r1] * m[c2][r2] - m[c2][r1] * m[c1][r2]) * inv;
        };
        draw.normal_x = { cof (0, 0), cof (0, 1), cof (0, 2), 0 };
        draw.normal_y = { cof (1, 0), cof (1, 1), cof (1, 2), 0 };
        draw.normal_z = { cof (2, 0), cof (2, 1), cof (2, 2), 0 };
        const Transient block = m_device->allocate (sizeof draw);
        std::memcpy (block.data, &draw, sizeof draw);

        DrawState current;
        bool first = true;
        for (const DrawList::Run& run : runs) {
          if (!run.count)
            continue;
          if (first || run.state != current) {
            m_device->set_pipeline (uber (run.state));
            current = run.state;
            first = false;
          }
          m_device->set_buffer (0, m_frame_block);
          if (baked)
            m_device->set_buffer (1, baked);
          else
            m_device->set_buffer (1, streamed);
          m_device->set_buffer (2, block);
          m_device->set_texture (0, texture_or_white (run.texture));
          m_device->draw (run.count, 1, run.first);
        }
      }

      Texture texture_or_white (const render::Texture* texture) const {
        return texture ? static_cast<const NhalTexture*> (texture)->handle
                       : m_white;
      }

      Texture texture_or_white (const render::TexturePtr& texture) const {
        return texture_or_white (texture.get ());
      }

      void make_targets () {
        for (Texture t : { m_scene_color, m_scene_motion, m_scene_depth,
                           m_history[0], m_history[1] })
          if (t)
            m_device->destroy (t);
        m_width = m_device->surface_width ();
        m_height = m_device->surface_height ();
        // The scene at half the drawable's size per axis, upscaled
        // temporally.
        m_scene_width = std::max (1u, m_width / 2);
        m_scene_height = std::max (1u, m_height / 2);
        m_scene_color = m_device->create_texture (
          { m_scene_width, m_scene_height, Format::rgba16_float,
            usage_render_target | usage_sampled, 1, "scene" });
        m_scene_motion = m_device->create_texture (
          { m_scene_width, m_scene_height, Format::rg16_float,
            usage_render_target | usage_sampled, 1, "scene motion" });
        m_scene_depth = m_device->create_texture (
          { m_scene_width, m_scene_height, Format::d32_float,
            usage_depth | usage_sampled, 1, "scene depth" });
        for (Texture& t : m_history)
          t = m_device->create_texture (
            { m_width, m_height, Format::rgba16_float,
              usage_render_target | usage_sampled, 1, "temporal history" });
        m_restart = true;
      }

      void open_scene () {
        if (m_scene_open || m_resolved)
          return;
        RenderPassDesc pass;
        pass.label = "scene";
        pass.color_count = 2;
        const auto& fog = m_params.clear_color;
        auto lin = [] (float x) { return std::pow (std::max (x, 0.0f), 2.2f); };
        pass.colors[0] = { m_scene_color, Load::clear, Store::store,
                           { lin (fog.red), lin (fog.green), lin (fog.blue),
                             1 } };
        pass.colors[1] = { m_scene_motion, Load::clear, Store::store,
                           { 0, 0, 0, 0 } };
        pass.depth = { m_scene_depth, Load::clear, Store::store, 0.0f };
        m_device->begin_render_pass (pass);
        m_scene_open = true;
      }

      void open_present () {
        if (m_presented)
          return;
        reconstruct_scene ();
        RenderPassDesc pass;
        pass.label = "present";
        pass.color_count = 1;
        pass.colors[0] = { m_device->backbuffer (), Load::discard,
                           Store::store };
        m_device->begin_render_pass (pass);
        m_device->set_pipeline (m_present);
        shaders::present::Present present {};
        present.grade = { std::max (m_params.exposure_bias, 0.01f),
                          m_device->surface_format () == Format::rgba16_float
                            ? 0.0f
                            : 1.0f,
                          std::fmod (m_params.time, 1000.0f), 0 };
        m_device->set_uniforms (0, present);
        m_device->set_buffer (1, m_exposure_value);
        m_device->set_texture (0, m_image);
        m_device->draw (3);
        m_presented = true;
      }

      std::unique_ptr<Device> m_device;
      float m_scale;
      ProgramCode m_terrain_code, m_sky_code, m_uber_code, m_hud_code,
        m_resolve_code, m_present_code, m_slug_text_code;
      Pipeline m_terrain, m_sky, m_resolve, m_present, m_hud, m_slug_text;
      ProgramCode m_forest_code;
      std::string m_forest_cull_code;
      std::vector<unsigned char> m_forest_cull_dxil;
      Pipeline m_forest, m_forest_cull, m_exposure;
      ProgramCode m_terrain_shadow_code, m_forest_shadow_code;
      Pipeline m_terrain_shadow, m_forest_shadow;
      Texture m_shadow_map;
      Buffer m_shadow_candidates, m_shadow_arguments;
      Transient m_shadow_forest_block;
      FrameBlock m_frame_values {};
      std::string m_exposure_code;
      std::vector<unsigned char> m_exposure_dxil;
      Buffer m_exposure_value;
      Buffer m_trees, m_tree_candidates, m_tree_arguments, m_tree_indices;
      std::uint32_t m_tree_count = 0;
      float m_tree_period[2] {};
      std::uint32_t m_tree_class_first[forest_classes] {};
      std::uint32_t m_tree_class_count[forest_classes] {};
      Transient m_forest_block;
      render::TextList m_hud_text;
      std::unordered_map<int, Pipeline> m_uber;
      Texture m_white;

      render::TerrainParams m_terrain_params {};
      bool m_have_terrain = false;
      Texture m_heights, m_normals, m_landscape, m_ground;
      render::TexturePtr m_grass, m_dirt, m_rock, m_snow;
      Buffer m_chunk_indices[lod_count], m_patch_indices[lod_count];
      std::uint32_t m_chunk_index_count[lod_count] {};
      std::uint32_t m_patch_index_count[lod_count] {};

      std::uint32_t m_width = 0, m_height = 0;
      std::uint32_t m_scene_width = 0, m_scene_height = 0;
      Texture m_scene_color, m_scene_motion, m_scene_depth, m_history[2];
      Texture m_image;

      FrameParams m_params {};
      Transient m_frame_block;
      Mat4 m_previous_view_proj;
      float m_previous_time = 0;
      std::uint32_t m_frame = 0;
      bool m_restart = true;
      bool m_scene_open = false, m_resolved = false, m_presented = false;
      std::map<std::uint64_t, Mat4> m_previous_models, m_current_models;
      std::string m_screenshot;
      std::map<std::string, double> m_timing_sums;
      int m_timing_frames = 0;
    };
  }

  std::unique_ptr<render::Renderer>
  create_renderer (std::unique_ptr<Device> device,
                   const WorldShaders& shaders,
                   float scale) {
    return std::make_unique<NhalRenderer> (std::move (device), shaders,
                                           scale);
  }
}
