// moppe's renderer over NHAL. A frame records, in the game's order: the
// scene (terrain, sky, draw lists and meshes) into a jittered RGBA16F
// colour, RG16F motion, and reversed-Z depth at the scene's scale; the
// temporal resolve into a history at the drawable's size; then the tonemap
// and the HUD into the drawable. Water, the forest's mesh-shader organs,
// undergrowth, dust, shadows, and the post effects are not drawn yet.
#include <moppe/nhal/renderer/nhal_renderer.hh>

#include <moppe/render/draw.hh>
#include <moppe/render/slug.hh>
#include <moppe/render/text.hh>
#include <moppe/render/texture_pixels.hh>
#include <moppe/render/types.hh>

// Generated by luv-shaderc from shaders/world.lisp.
#include <hud.hh>
#include <present.hh>
#include <resolve.hh>
#include <sky.hh>
#include <slug_text.hh>
#include <terrain.hh>
#include <uber.hh>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <map>
#include <string>
#include <unordered_map>
#include <vector>

namespace moppe::nhal {
  namespace {
    using render::ChunkDraw;
    using render::DrawList;
    using render::DrawState;
    using render::FrameParams;

    using FrameBlock = shaders::terrain::Frame;
    static_assert (sizeof (FrameBlock) == sizeof (shaders::uber::Frame));
    static_assert (sizeof (FrameBlock) == sizeof (shaders::sky::Frame));
    static_assert (sizeof (FrameBlock) == sizeof (shaders::resolve::Frame));

    // The terrain's chunk levels, as the game's culling chooses them: a
    // step of source samples per rendered cell and vertices per chunk row.
    constexpr int chunk_cells = render::terrain_chunk_cells;
    constexpr int lod_count = int (render::TerrainLod::Count);
    constexpr float lod_step[lod_count] = { 0.25f, 1.0f, 2.0f, 4.0f, 8.0f };
    constexpr int lod_verts[lod_count] = { chunk_cells * 4 + 1, chunk_cells + 1,
                                           chunk_cells / 2 + 1,
                                           chunk_cells / 4 + 1,
                                           chunk_cells / 8 + 1 };

    int patch_verts (int lod) {
      return (lod_verts[lod] - 1) * render::terrain_patch_cells / chunk_cells
             + 1;
    }

    std::array<float, 16> matrix (const Mat4& m) {
      std::array<float, 16> out;
      for (int i = 0; i < 16; ++i)
        out[i] = m.element (i);
      return out;
    }

    std::array<float, 4> lanes (const Vec3& v, float w = 0) {
      return { v[0], v[1], v[2], w };
    }

    std::array<float, 4> linear (DisplayColor c, float w = 0) {
      auto lin = [] (float x) { return std::pow (std::max (x, 0.0f), 2.2f); };
      return { lin (c.red), lin (c.green), lin (c.blue), w };
    }

    float halton (std::uint32_t index, std::uint32_t base) {
      float fraction = 1, result = 0;
      while (index > 0) {
        fraction /= float (base);
        result += fraction * float (index % base);
        index /= base;
      }
      return result;
    }

    // -- screenshots: a small, uncompressed PNG ---------------------------

    std::uint32_t crc (const std::uint8_t* data, std::size_t size,
                       std::uint32_t c = 0xffffffffu) {
      static std::uint32_t table[256];
      if (!table[1])
        for (std::uint32_t n = 0; n < 256; ++n) {
          std::uint32_t v = n;
          for (int k = 0; k < 8; ++k)
            v = v & 1 ? 0xedb88320u ^ (v >> 1) : v >> 1;
          table[n] = v;
        }
      for (std::size_t i = 0; i < size; ++i)
        c = table[(c ^ data[i]) & 255] ^ (c >> 8);
      return c;
    }

    void write_png (const std::string& path, std::uint32_t width,
                    std::uint32_t height,
                    const std::vector<std::uint8_t>& rgb) {
      std::vector<std::uint8_t> raw;
      raw.reserve ((width * 3 + 1) * height);
      for (std::uint32_t y = 0; y < height; ++y) {
        raw.push_back (0);
        raw.insert (raw.end (), rgb.begin () + std::size_t (y) * width * 3,
                    rgb.begin () + std::size_t (y + 1) * width * 3);
      }
      // zlib with stored deflate blocks.
      std::vector<std::uint8_t> z { 0x78, 0x01 };
      std::uint32_t a = 1, b = 0;
      for (std::size_t at = 0; at < raw.size ();) {
        const std::size_t n = std::min<std::size_t> (65535, raw.size () - at);
        z.push_back (at + n == raw.size () ? 1 : 0);
        z.push_back (n & 255);
        z.push_back (n >> 8);
        z.push_back (~n & 255);
        z.push_back ((~n >> 8) & 255);
        z.insert (z.end (), raw.begin () + at, raw.begin () + at + n);
        for (std::size_t i = at; i < at + n; ++i) {
          a = (a + raw[i]) % 65521;
          b = (b + a) % 65521;
        }
        at += n;
      }
      const std::uint32_t adler = (b << 16) | a;
      for (int s = 24; s >= 0; s -= 8)
        z.push_back ((adler >> s) & 255);

      FILE* file = std::fopen (path.c_str (), "wb");
      if (!file)
        return;
      auto u32 = [] (std::vector<std::uint8_t>& v, std::uint32_t x) {
        for (int s = 24; s >= 0; s -= 8)
          v.push_back ((x >> s) & 255);
      };
      auto chunk = [&] (const char* type, const std::vector<std::uint8_t>& d) {
        std::vector<std::uint8_t> out;
        u32 (out, std::uint32_t (d.size ()));
        out.insert (out.end (), type, type + 4);
        out.insert (out.end (), d.begin (), d.end ());
        u32 (out, ~crc (out.data () + 4, out.size () - 4));
        std::fwrite (out.data (), 1, out.size (), file);
      };
      const std::uint8_t signature[8] = { 137, 80, 78, 71, 13, 10, 26, 10 };
      std::fwrite (signature, 1, 8, file);
      std::vector<std::uint8_t> header;
      u32 (header, width);
      u32 (header, height);
      header.insert (header.end (), { 8, 2, 0, 0, 0 });
      chunk ("IHDR", header);
      chunk ("IDAT", z);
      chunk ("IEND", {});
      std::fclose (file);
    }

    float half_to_float (std::uint16_t h) {
      const std::uint32_t e = (h >> 10) & 31, m = h & 1023;
      const float v = e == 0 ? std::ldexp (float (m), -24)
                      : e == 31 ? 65504.0f
                                : std::ldexp (float (m | 1024), int (e) - 25);
      return (h >> 15) ? -v : v;
    }

    // -- resources the game holds -----------------------------------------

    struct NhalTexture final : render::Texture {
      Device* device = nullptr;
      nhal::Texture handle;
      ~NhalTexture () override { device->destroy (handle); }
    };

    struct NhalMesh final : render::Mesh {
      Device* device = nullptr;
      Buffer vertices;
      std::vector<DrawList::Run> runs;
      ~NhalMesh () override {
        if (vertices)
          device->destroy (vertices);
      }
    };

    struct NhalGlyphSet final : render::GlyphSet {
      Device* device = nullptr;
      Buffer curves, bands;
      ~NhalGlyphSet () override {
        device->destroy (curves);
        device->destroy (bands);
      }
    };

    // Owned copies of a program's stage code, which pipelines made on
    // demand need after construction.
    struct ProgramCode {
      std::string msl[2];
      std::vector<unsigned char> dxil[2];

      void keep (const StageCode (&stages)[2]) {
        for (int i = 0; i < 2; ++i) {
          msl[i] = std::string (stages[i].msl);
          dxil[i].assign (stages[i].dxil.begin (), stages[i].dxil.end ());
        }
      }
      StageCode stage (int i) const { return { msl[i], dxil[i] }; }
    };

    class NhalRenderer final : public render::Renderer {
    public:
      NhalRenderer (std::unique_ptr<Device> device,
                    const WorldShaders& shaders, float scale)
        : m_device (std::move (device)), m_scale (scale) {
        m_terrain_code.keep (shaders.terrain);
        m_sky_code.keep (shaders.sky);
        m_uber_code.keep (shaders.uber);
        m_hud_code.keep (shaders.hud);
        m_resolve_code.keep (shaders.resolve);
        m_present_code.keep (shaders.present);
        m_slug_text_code.keep (shaders.slug_text);
        make_pipelines ();
        const std::uint8_t white[4] = { 255, 255, 255, 255 };
        m_white = m_device->create_texture ({ 1, 1, Format::rgba8_unorm,
                                              usage_sampled, 1, "white" });
        m_device->write_texture (m_white, std::as_bytes (std::span (white)));
        std::cerr << "moppe: NHAL renderer on " << m_device->info ().backend
                  << " (" << m_device->info ().adapter << ")" << std::endl;
      }

      ~NhalRenderer () override {
        m_device->wait_idle ();
      }

      // -- resources ------------------------------------------------------

      render::TexturePtr create_texture (const render::TextureDesc& desc,
                                         const void* pixels) override {
        auto texture = std::make_shared<NhalTexture> ();
        texture->device = m_device.get ();
        texture->width = desc.width;
        texture->height = desc.height;
        texture->handle = m_device->create_texture (
          { std::uint32_t (desc.width), std::uint32_t (desc.height),
            Format::rgba8_unorm_srgb, usage_sampled, 1, "game texture" });
        const std::size_t texels = std::size_t (desc.width) * desc.height;
        std::vector<std::uint8_t> rgba (texels * 4, 255);
        const auto* source = static_cast<const std::uint8_t*> (pixels);
        if (source && desc.format == render::TextureFormat::RGB8) {
          for (std::size_t i = 0; i < texels; ++i)
            std::memcpy (&rgba[i * 4], &source[i * 3], 3);
        } else if (source) {
          std::memcpy (rgba.data (), source, rgba.size ());
        }
        m_device->write_texture (texture->handle,
                                 std::as_bytes (std::span (rgba)));
        return texture;
      }

      render::MeshPtr create_mesh (const DrawList& recorded) override {
        auto mesh = std::make_shared<NhalMesh> ();
        mesh->device = m_device.get ();
        const auto& vertices = recorded.vertices ();
        if (!vertices.empty ())
          mesh->vertices = m_device->create_buffer (
            { .size = vertices.size () * sizeof (render::Vertex),
              .label = "mesh" },
            std::as_bytes (std::span (vertices)));
        mesh->runs = recorded.runs ();
        return mesh;
      }

      render::GlyphSetPtr
      create_glyph_set (const render::SlugGlyphData& data) override {
        if (data.curves.empty () || data.bands.empty ())
          return nullptr;
        auto set = std::make_shared<NhalGlyphSet> ();
        set->device = m_device.get ();
        set->curves = m_device->create_buffer (
          { .size = data.curves.size () * sizeof (render::SlugCurveTexel),
            .label = "slug curves" },
          std::as_bytes (std::span (data.curves)));
        set->bands = m_device->create_buffer (
          { .size = data.bands.size () * sizeof (std::uint32_t),
            .label = "slug bands" },
          std::as_bytes (std::span (data.bands)));
        return set;
      }

      // -- world setup ----------------------------------------------------

      void set_terrain (const render::TerrainParams& params,
                        std::span<const terrain::SurfaceElevation> heights,
                        std::span<const terrain::TerrainNormal> normals)
        override {
        m_terrain_params = params;
        const std::uint32_t w = params.width, h = params.height;
        for (Texture* t : { &m_heights, &m_normals })
          if (*t)
            m_device->destroy (*t);
        m_heights = m_device->create_texture (
          { w, h, Format::r32_float, usage_sampled, 1, "terrain heights" });
        static_assert (sizeof (terrain::SurfaceElevation) == sizeof (float));
        m_device->write_texture (m_heights, std::as_bytes (heights));
        // Normals: x and z as RG16 snorm; the shader rebuilds y.
        m_normals = m_device->create_texture (
          { w, h, Format::rg16_snorm, usage_sampled, 1, "terrain normals" });
        std::vector<std::int16_t> packed (normals.size () * 2);
        for (std::size_t i = 0; i < normals.size (); ++i) {
          const Vec3 n = normals[i].numerical_value_in (mp_units::one);
          packed[i * 2] = std::int16_t (std::clamp (n[0], -1.0f, 1.0f)
                                        * 32767.0f);
          packed[i * 2 + 1] = std::int16_t (std::clamp (n[2], -1.0f, 1.0f)
                                            * 32767.0f);
        }
        m_device->write_texture (m_normals,
                                 std::as_bytes (std::span (packed)));

        // Strip index templates per level, whole chunks and patches, with
        // the all-ones restart between rows.
        if (!m_chunk_indices[0]) {
          auto strips = [&] (int verts, const char* label) {
            std::vector<std::uint32_t> indices;
            for (int row = 0; row + 1 < verts; ++row) {
              for (int x = 0; x < verts; ++x) {
                indices.push_back (std::uint32_t (row * verts + x));
                indices.push_back (std::uint32_t ((row + 1) * verts + x));
              }
              indices.push_back (0xffffffffu);
            }
            const Buffer buffer = m_device->create_buffer (
              { .size = indices.size () * 4, .label = label },
              std::as_bytes (std::span (indices)));
            return std::pair (buffer, std::uint32_t (indices.size ()));
          };
          for (int lod = 0; lod < lod_count; ++lod) {
            std::tie (m_chunk_indices[lod], m_chunk_index_count[lod]) =
              strips (lod_verts[lod], "terrain chunk strips");
            std::tie (m_patch_indices[lod], m_patch_index_count[lod]) =
              strips (patch_verts (lod), "terrain patch strips");
          }
        }
        m_have_terrain = true;
      }

      void set_terrain_topology_overlay (bool) override {}

      void set_terrain_textures (render::TexturePtr grass,
                                 render::TexturePtr dirt,
                                 render::TexturePtr rock,
                                 render::TexturePtr snow) override {
        m_grass = grass;
        m_dirt = dirt;
        m_rock = rock;
        m_snow = snow;
      }

      void set_terrain_overlay (const render::TerrainOverlayParams&,
                                std::span<const float>) override {}
      void clear_terrain_overlay () override {}
      void render_terrain_shadow (const Mat4&, bool) override {}
      void set_ocean (const render::OceanSetup&,
                      const render::TexturePixels&) override {}

      void set_terrain_materials (const render::TexturePixels& landscape,
                                  const render::TexturePixels& ground,
                                  bool) override {
        auto sheet = [&] (Texture& texture,
                          const render::TexturePixels& pixels,
                          const char* label) {
          if (texture)
            m_device->destroy (texture);
          texture = {};
          if (pixels.empty ()
              || pixels.format () != render::PixelFormat::rgba8unorm)
            return;
          texture = m_device->create_texture (
            { std::uint32_t (pixels.width ()), std::uint32_t (pixels.height ()),
              Format::rgba8_unorm, usage_sampled, 1, label });
          std::vector<std::byte> bytes (pixels.byte_size ());
          pixels.write_into (bytes.data ());
          m_device->write_texture (texture, bytes);
        };
        sheet (m_landscape, landscape, "landscape materials");
        sheet (m_ground, ground, "ground materials");
      }

      // -- a frame --------------------------------------------------------

      void offer_platform_drawable (void* drawable) override {
        m_device->offer_drawable (drawable);
      }

      bool begin_frame (const FrameParams& params) override {
        if (!m_device->begin_frame ())
          return false;
        if (m_width != m_device->surface_width ()
            || m_height != m_device->surface_height ())
          make_targets ();
        m_params = params;
        m_scene_open = m_resolved = m_presented = false;

        const Mat4 view_proj = params.proj * params.view;
        if (m_restart)
          m_previous_view_proj = view_proj, m_previous_time = params.time;
        const float tan_x = 1.0f / params.proj.at (0, 0);
        const float tan_y = 1.0f / params.proj.at (1, 1);
        const std::uint32_t phase = m_frame++ % 16 + 1;

        FrameBlock frame {};
        frame.view_proj = matrix (view_proj);
        frame.previous_view_proj = matrix (m_previous_view_proj);
        frame.camera_position = lanes (params.camera_pos, params.time);
        frame.sun_direction = lanes (params.sun_dir, params.cloud_cover);
        frame.sun_diffuse = linear (params.sun_diffuse);
        frame.sun_specular = linear (params.sun_specular);
        frame.ambient = linear (params.ambient);
        frame.fog_color = linear (params.clear_color, params.fog_scale);
        frame.relief = { m_terrain_params.sea_level,
                         m_terrain_params.land_relief, m_previous_time, 0 };
        frame.view_right = lanes (params.cam_right * tan_x);
        frame.view_up = lanes (params.cam_up * tan_y);
        frame.view_forward = lanes (params.cam_forward);
        frame.temporal = { float (m_scene_width), float (m_scene_height),
                           (halton (phase, 2) - 0.5f) * 2
                             / float (m_scene_width),
                           (halton (phase, 3) - 0.5f) * 2
                             / float (m_scene_height) };
        frame.temporal_blend = { m_restart ? 1.0f : 0.1f, 0, float (m_width),
                                 float (m_height) };
        m_frame_block = m_device->allocate (sizeof frame);
        std::memcpy (m_frame_block.data, &frame, sizeof frame);

        m_previous_view_proj = view_proj;
        m_previous_time = params.time;
        m_restart = false;
        return true;
      }

      void draw_terrain (const ChunkDraw* chunks, int count) override {
        if (!m_have_terrain || count <= 0)
          return;
        open_scene ();
        m_device->set_pipeline (m_terrain);
        m_device->set_buffer (0, m_frame_block);
        shaders::terrain::Terrain terrain {};
        const auto& p = m_terrain_params;
        terrain.scale = { p.scale[0], p.scale[1], p.scale[2], p.tex_scale };
        terrain.fields = { m_landscape && m_ground ? 1.0f : 0.0f, 0, 0, 0 };
        terrain.size = { float (p.width), float (p.height), 0, 0 };
        m_device->set_uniforms (1, terrain);
        m_device->set_texture (0, m_heights);
        m_device->set_texture (1, m_normals);
        m_device->set_texture (2, texture_or_white (m_grass));
        m_device->set_texture (3, texture_or_white (m_dirt));
        m_device->set_texture (4, texture_or_white (m_rock));
        m_device->set_texture (5, texture_or_white (m_snow));
        m_device->set_texture (6, m_landscape ? m_landscape : m_white);
        m_device->set_texture (7, m_ground ? m_ground : m_white);
        for (int i = 0; i < count; ++i) {
          const ChunkDraw& c = chunks[i];
          const int lod = std::clamp (int (c.lod), 0, lod_count - 1);
          const bool patch = c.cells == render::terrain_patch_cells;
          shaders::terrain::Chunk chunk {};
          chunk.placement = { float (c.x0), float (c.z0), lod_step[lod],
                              float (patch ? patch_verts (lod)
                                           : lod_verts[lod]) };
          chunk.morph = { c.morph_start, c.morph_end,
                          lod_step[std::min (lod + 1, lod_count - 1)], 0 };
          chunk.offset = { c.offset_x, 0, c.offset_z, 0 };
          m_device->set_uniforms (2, chunk);
          m_device->draw_indexed (
            patch ? m_patch_indices[lod] : m_chunk_indices[lod],
            IndexType::uint32,
            patch ? m_patch_index_count[lod] : m_chunk_index_count[lod]);
        }
      }

      void draw_sky (const render::SkyParams&) override {
        open_scene ();
        m_device->set_pipeline (m_sky);
        m_device->set_buffer (0, m_frame_block);
        m_device->draw (3);
      }

      void draw_ocean (const render::OceanParams&) override {}
      void draw_waterfalls (const render::Mesh&, const Mat4&) override {}

      void draw_list (const DrawList& list, std::uint64_t) override {
        if (list.empty ())
          return;
        open_scene ();
        const Transient vertices =
          m_device->upload (std::span (list.vertices ()));
        draw_runs (vertices, Buffer {}, list.runs (), Mat4 {}, Mat4 {});
      }

      void draw_mesh (const render::Mesh& mesh, const Mat4& model,
                      std::uint64_t motion_id) override {
        const auto& m = static_cast<const NhalMesh&> (mesh);
        if (!m.vertices)
          return;
        open_scene ();
        Mat4 previous = model;
        if (motion_id) {
          if (auto found = m_previous_models.find (motion_id);
              found != m_previous_models.end ())
            previous = found->second;
          m_current_models[motion_id] = model;
        }
        draw_runs ({}, m.vertices, m.runs, model, previous);
      }

      void reconstruct_scene () override {
        if (m_resolved)
          return;
        open_scene ();
        m_device->end_render_pass ();
        m_scene_open = false;
        Texture& previous = m_history[m_frame % 2];
        Texture& next = m_history[(m_frame + 1) % 2];
        RenderPassDesc pass;
        pass.label = "temporal resolve";
        pass.color_count = 1;
        pass.colors[0] = { next, Load::discard, Store::store };
        m_device->begin_render_pass (pass);
        m_device->set_pipeline (m_resolve);
        m_device->set_buffer (0, m_frame_block);
        m_device->set_texture (0, m_scene_color);
        m_device->set_texture (1, m_scene_motion);
        m_device->set_texture (2, m_scene_depth);
        m_device->set_texture (3, previous);
        m_device->draw (3);
        m_device->end_render_pass ();
        m_image = next;
        m_resolved = true;
      }

      void apply_underwater (float) override {}
      void apply_motion_blur (float) override {}
      void apply_scene_blur () override {}

      void draw_hud_text (const render::TextList& text) override {
        m_hud_text = text;
      }

      // The HUD's draw list, then its Slug text over it.
      void draw_hud (const DrawList& list) override {
        open_present ();
        shaders::hud::Hud hud {};
        hud.projection = matrix (Mat4::hud_ortho (width_pts (), height_pts ()));
        hud.output = { m_device->surface_format () == Format::rgba16_float
                         ? 1.0f
                         : 0.0f,
                       m_scale, 0, 0 };
        if (!list.empty ()) {
          m_device->set_pipeline (m_hud);
          m_device->set_uniforms (0, hud);
          m_device->set_buffer (
            1, m_device->upload (std::span (list.vertices ())));
          for (const DrawList::Run& run : list.runs ()) {
            if (!run.count)
              continue;
            m_device->set_texture (0, texture_or_white (run.texture));
            m_device->draw (run.count, 1, run.first);
          }
        }
        if (!m_hud_text.empty ()) {
          m_device->set_pipeline (m_slug_text);
          m_device->set_uniforms (0, hud);
          const auto& quads = m_hud_text.quads ();
          for (const render::TextList::Run& run : m_hud_text.runs ()) {
            const auto* glyphs =
              static_cast<const NhalGlyphSet*> (run.glyphs.get ());
            if (!glyphs || !run.count)
              continue;
            // Each run's quads in a slice of their own: Direct3D's instance
            // index does not count from a draw's first instance.
            m_device->set_buffer (
              1, m_device->upload (std::span (quads).subspan (run.first,
                                                              run.count)));
            m_device->set_buffer (2, glyphs->curves);
            m_device->set_buffer (3, glyphs->bands);
            m_device->draw (6, run.count);
          }
          m_hud_text.clear ();
        }
      }

      void request_screenshot (const std::string& path) override {
        m_screenshot = path;
      }

      void end_frame () override {
        open_present ();
        m_device->end_render_pass ();
        if (!m_screenshot.empty ()) {
          m_device->capture_frame ([path = m_screenshot] (
                                     const Capture& capture) {
            const Format format = capture.format;
            std::vector<std::uint8_t> rgb (std::size_t (capture.width)
                                           * capture.height * 3);
            for (std::uint32_t y = 0; y < capture.height; ++y)
              for (std::uint32_t x = 0; x < capture.width; ++x) {
                const std::byte* p = capture.pixels.data ()
                                     + std::size_t (y) * capture.row_bytes
                                     + std::size_t (x)
                                         * bytes_per_pixel (format);
                std::uint8_t* out = &rgb[(std::size_t (y) * capture.width + x)
                                         * 3];
                if (format == Format::rgba16_float) {
                  for (int c = 0; c < 3; ++c) {
                    std::uint16_t h;
                    std::memcpy (&h, p + c * 2, 2);
                    const float v = std::clamp (half_to_float (h), 0.0f, 1.0f);
                    out[c] = std::uint8_t (std::pow (v, 1 / 2.2f) * 255 + 0.5f);
                  }
                } else {
                  const bool bgra = format == Format::bgra8_unorm;
                  out[0] = std::uint8_t (p[bgra ? 2 : 0]);
                  out[1] = std::uint8_t (p[1]);
                  out[2] = std::uint8_t (p[bgra ? 0 : 2]);
                }
              }
            write_png (path, capture.width, capture.height, rgb);
            std::cerr << "moppe: wrote " << path << std::endl;
          });
          m_screenshot.clear ();
          // Hosts may quit straight after the frame they asked to capture,
          // so the readback completes here rather than next frame.
          m_device->end_frame ();
          m_device->wait_idle ();
        } else {
          m_device->end_frame ();
        }
        m_previous_models.swap (m_current_models);
        m_current_models.clear ();
      }

      void reset_temporal_state () override { m_restart = true; }

      int width_pts () const override {
        return int (float (m_device->surface_width ()) / m_scale);
      }
      int height_pts () const override {
        return int (float (m_device->surface_height ()) / m_scale);
      }
      float scale_factor () const override { return m_scale; }

    private:
      void make_pipelines () {
        RenderPipelineDesc scene;
        scene.color_formats[0] = Format::rgba16_float;
        scene.color_formats[1] = Format::rg16_float;
        scene.color_count = 2;
        scene.depth_format = Format::d32_float;
        scene.cull = Cull::back;

        RenderPipelineDesc terrain = scene;
        terrain.program = &shaders::terrain::program;
        terrain.vertex = m_terrain_code.stage (0);
        terrain.fragment = m_terrain_code.stage (1);
        terrain.topology = Topology::triangle_strip;
        m_terrain = m_device->create_render_pipeline (terrain);

        RenderPipelineDesc sky = scene;
        sky.program = &shaders::sky::program;
        sky.vertex = m_sky_code.stage (0);
        sky.fragment = m_sky_code.stage (1);
        sky.cull = Cull::none;
        sky.depth_write = false;
        m_sky = m_device->create_render_pipeline (sky);

        RenderPipelineDesc resolve;
        resolve.program = &shaders::resolve::program;
        resolve.vertex = m_resolve_code.stage (0);
        resolve.fragment = m_resolve_code.stage (1);
        resolve.color_formats[0] = Format::rgba16_float;
        m_resolve = m_device->create_render_pipeline (resolve);

        RenderPipelineDesc present;
        present.program = &shaders::present::program;
        present.vertex = m_present_code.stage (0);
        present.fragment = m_present_code.stage (1);
        present.color_formats[0] = m_device->surface_format ();
        m_present = m_device->create_render_pipeline (present);

        RenderPipelineDesc hud = present;
        hud.program = &shaders::hud::program;
        hud.vertex = m_hud_code.stage (0);
        hud.fragment = m_hud_code.stage (1);
        hud.blend[0] = Blend::alpha;
        m_hud = m_device->create_render_pipeline (hud);

        RenderPipelineDesc text = hud;
        text.program = &shaders::slug_text::program;
        text.vertex = m_slug_text_code.stage (0);
        text.fragment = m_slug_text_code.stage (1);
        m_slug_text = m_device->create_render_pipeline (text);
      }

      // The draw-list pipeline for a run's fixed-function state.
      Pipeline uber (const DrawState& state) {
        const int key = (state.blend ? 1 : 0) | (state.additive ? 2 : 0)
                        | (state.depth_test ? 4 : 0)
                        | (state.depth_write ? 8 : 0) | (state.cull ? 16 : 0);
        Pipeline& pipeline = m_uber[key];
        if (pipeline)
          return pipeline;
        RenderPipelineDesc desc;
        desc.program = &shaders::uber::program;
        desc.vertex = m_uber_code.stage (0);
        desc.fragment = m_uber_code.stage (1);
        desc.color_formats[0] = Format::rgba16_float;
        desc.color_formats[1] = Format::rg16_float;
        desc.color_count = 2;
        desc.blend[0] = state.additive ? Blend::additive
                        : state.blend  ? Blend::alpha
                                       : Blend::none;
        desc.depth_format = Format::d32_float;
        desc.depth_compare = state.depth_test ? CompareOp::greater_equal
                                              : CompareOp::always;
        desc.depth_write = state.depth_write;
        desc.cull = state.cull ? Cull::back : Cull::none;
        pipeline = m_device->create_render_pipeline (desc);
        return pipeline;
      }

      void draw_runs (const Transient& streamed, Buffer baked,
                      const std::vector<DrawList::Run>& runs,
                      const Mat4& model, const Mat4& previous) {
        shaders::uber::Draw draw {};
        draw.model = matrix (model);
        draw.previous_model = matrix (previous);
        // The normal matrix: the inverse transpose of the model's 3x3.
        float m[3][3];
        for (int c = 0; c < 3; ++c)
          for (int r = 0; r < 3; ++r)
            m[c][r] = model.at (c, r);
        const float det = m[0][0] * (m[1][1] * m[2][2] - m[2][1] * m[1][2])
                          - m[1][0] * (m[0][1] * m[2][2] - m[2][1] * m[0][2])
                          + m[2][0] * (m[0][1] * m[1][2] - m[1][1] * m[0][2]);
        const float inv = std::abs (det) > 1e-12f ? 1.0f / det : 1.0f;
        auto cof = [&] (int c, int r) {
          const int c1 = (c + 1) % 3, c2 = (c + 2) % 3;
          const int r1 = (r + 1) % 3, r2 = (r + 2) % 3;
          return (m[c1][r1] * m[c2][r2] - m[c2][r1] * m[c1][r2]) * inv;
        };
        draw.normal_x = { cof (0, 0), cof (0, 1), cof (0, 2), 0 };
        draw.normal_y = { cof (1, 0), cof (1, 1), cof (1, 2), 0 };
        draw.normal_z = { cof (2, 0), cof (2, 1), cof (2, 2), 0 };
        const Transient block = m_device->allocate (sizeof draw);
        std::memcpy (block.data, &draw, sizeof draw);

        DrawState current;
        bool first = true;
        for (const DrawList::Run& run : runs) {
          if (!run.count)
            continue;
          if (first || run.state != current) {
            m_device->set_pipeline (uber (run.state));
            current = run.state;
            first = false;
          }
          m_device->set_buffer (0, m_frame_block);
          if (baked)
            m_device->set_buffer (1, baked);
          else
            m_device->set_buffer (1, streamed);
          m_device->set_buffer (2, block);
          m_device->set_texture (0, texture_or_white (run.texture));
          m_device->draw (run.count, 1, run.first);
        }
      }

      Texture texture_or_white (const render::Texture* texture) const {
        return texture ? static_cast<const NhalTexture*> (texture)->handle
                       : m_white;
      }

      Texture texture_or_white (const render::TexturePtr& texture) const {
        return texture_or_white (texture.get ());
      }

      void make_targets () {
        for (Texture t : { m_scene_color, m_scene_motion, m_scene_depth,
                           m_history[0], m_history[1] })
          if (t)
            m_device->destroy (t);
        m_width = m_device->surface_width ();
        m_height = m_device->surface_height ();
        // The scene at half the drawable's size per axis, upscaled
        // temporally.
        m_scene_width = std::max (1u, m_width / 2);
        m_scene_height = std::max (1u, m_height / 2);
        m_scene_color = m_device->create_texture (
          { m_scene_width, m_scene_height, Format::rgba16_float,
            usage_render_target | usage_sampled, 1, "scene" });
        m_scene_motion = m_device->create_texture (
          { m_scene_width, m_scene_height, Format::rg16_float,
            usage_render_target | usage_sampled, 1, "scene motion" });
        m_scene_depth = m_device->create_texture (
          { m_scene_width, m_scene_height, Format::d32_float,
            usage_depth | usage_sampled, 1, "scene depth" });
        for (Texture& t : m_history)
          t = m_device->create_texture (
            { m_width, m_height, Format::rgba16_float,
              usage_render_target | usage_sampled, 1, "temporal history" });
        m_restart = true;
      }

      void open_scene () {
        if (m_scene_open || m_resolved)
          return;
        RenderPassDesc pass;
        pass.label = "scene";
        pass.color_count = 2;
        const auto& fog = m_params.clear_color;
        auto lin = [] (float x) { return std::pow (std::max (x, 0.0f), 2.2f); };
        pass.colors[0] = { m_scene_color, Load::clear, Store::store,
                           { lin (fog.red), lin (fog.green), lin (fog.blue),
                             1 } };
        pass.colors[1] = { m_scene_motion, Load::clear, Store::store,
                           { 0, 0, 0, 0 } };
        pass.depth = { m_scene_depth, Load::clear, Store::store, 0.0f };
        m_device->begin_render_pass (pass);
        m_scene_open = true;
      }

      void open_present () {
        if (m_presented)
          return;
        reconstruct_scene ();
        RenderPassDesc pass;
        pass.label = "present";
        pass.color_count = 1;
        pass.colors[0] = { m_device->backbuffer (), Load::discard,
                           Store::store };
        m_device->begin_render_pass (pass);
        m_device->set_pipeline (m_present);
        shaders::present::Present present {};
        present.grade = { std::max (m_params.exposure_bias, 0.01f),
                          m_device->surface_format () == Format::rgba16_float
                            ? 0.0f
                            : 1.0f,
                          0, 0 };
        m_device->set_uniforms (0, present);
        m_device->set_texture (0, m_image);
        m_device->draw (3);
        m_presented = true;
      }

      std::unique_ptr<Device> m_device;
      float m_scale;
      ProgramCode m_terrain_code, m_sky_code, m_uber_code, m_hud_code,
        m_resolve_code, m_present_code, m_slug_text_code;
      Pipeline m_terrain, m_sky, m_resolve, m_present, m_hud, m_slug_text;
      render::TextList m_hud_text;
      std::unordered_map<int, Pipeline> m_uber;
      Texture m_white;

      render::TerrainParams m_terrain_params {};
      bool m_have_terrain = false;
      Texture m_heights, m_normals, m_landscape, m_ground;
      render::TexturePtr m_grass, m_dirt, m_rock, m_snow;
      Buffer m_chunk_indices[lod_count], m_patch_indices[lod_count];
      std::uint32_t m_chunk_index_count[lod_count] {};
      std::uint32_t m_patch_index_count[lod_count] {};

      std::uint32_t m_width = 0, m_height = 0;
      std::uint32_t m_scene_width = 0, m_scene_height = 0;
      Texture m_scene_color, m_scene_motion, m_scene_depth, m_history[2];
      Texture m_image;

      FrameParams m_params {};
      Transient m_frame_block;
      Mat4 m_previous_view_proj;
      float m_previous_time = 0;
      std::uint32_t m_frame = 0;
      bool m_restart = true;
      bool m_scene_open = false, m_resolved = false, m_presented = false;
      std::map<std::uint64_t, Mat4> m_previous_models, m_current_models;
      std::string m_screenshot;
    };
  }

  std::unique_ptr<render::Renderer>
  create_renderer (std::unique_ptr<Device> device,
                   const WorldShaders& shaders,
                   float scale) {
    return std::make_unique<NhalRenderer> (std::move (device), shaders,
                                           scale);
  }
}
