# -*- python -*-

import sys

Import('env')

libs = ['moppe-map', 'moppe-gfx', 'moppe-mov',
        'GLEW']

if sys.platform != 'darwin':
    libs.append('glut')

env.Program('moppe', ['main.cc', 'app.cc', 'gl.cc', 'util.cc'],
            LIBS=libs,
            LIBPATH=['..', '#/vendor/glew/lib'])
