# -*- python -*-

import sys

Import('env')

libs = ['moppe-map', 'moppe-gfx']

if sys.platform != 'darwin':
    libs.append('glut')

env.Program('moppe', ['main.cc', 'app.cc'],
            LIBS=libs,
            LIBPATH='..')
