"""Exports a rigid model's assemblies and points to C++.

    Blender -b models/bike.blend --python tools/figure/export_model.py -- \\
      bike_model

writes moppe/game/bike_model.{hh,cc} in namespace moppe::game::bike_model.

Every empty with a `moppe_mesh` property becomes a model_mesh::Mesh of
that name: its children's evaluated meshes (subdivision and bevels
applied) in the empty's own frame, converted to the game's (x right, y up,
z forward), with per-corner normals so smooth and hard-edged parts both
shade as modelled, and a palette entry per material (unlit when the
material's `moppe_unlit` is set). Every empty with a `moppe_point`
property becomes a Vec3 of its location in model space.
"""

import os
import sys

import bpy

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def game(v):
    return (v[0], v[2], -v[1])


def to_display(c):
    c = max(0.0, min(1.0, c))
    return c * 12.92 if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055


def f(x):
    s = f"{x:.4f}".rstrip("0")
    s = s + "0" if s.endswith(".") else s
    return ("0.0" if s in ("-0.0", "0.0") else s) + "f"


def triple(v):
    return "{" + ", ".join(f(x) for x in v) + "}"


def export_mesh(empty, graph, palette):
    to_local = empty.matrix_world.inverted()
    vertices, index, triangles = [], {}, []
    for obj in sorted(empty.children, key=lambda o: o.name):
        if obj.type != "MESH":
            continue
        evaluated = obj.evaluated_get(graph)
        mesh = evaluated.to_mesh()
        matrix = to_local @ obj.matrix_world
        turn = matrix.to_3x3().inverted().transposed()
        mesh.calc_loop_triangles()
        normals = mesh.corner_normals
        for t in mesh.loop_triangles:
            mat = mesh.materials[t.material_index]
            key = (mat.name,
                   tuple(round(to_display(c), 4)
                         for c in mat.diffuse_color[:3]),
                   bool(mat.get("moppe_unlit", False)))
            if key not in palette:
                palette.append(key)
            corners = []
            for loop in t.loops:
                v = mesh.loops[loop].vertex_index
                p = game(matrix @ mesh.vertices[v].co)
                n = game((turn @ normals[loop].vector).normalized())
                k = (obj.name, v, tuple(round(x, 3) for x in n))
                if k not in index:
                    index[k] = len(vertices)
                    vertices.append((p, n))
                corners.append(index[k])
            triangles.append((*corners, palette.index(key)))
        evaluated.to_mesh_clear()
    if len(vertices) > 65535:
        raise SystemExit(f"{empty.name}: too many vertices")
    return vertices, triangles


def main():
    stem = sys.argv[sys.argv.index("--") + 1]
    out_cc = os.path.join(ROOT, "moppe", "game", f"{stem}.cc")
    out_hh = os.path.join(ROOT, "moppe", "game", f"{stem}.hh")
    blend = os.path.basename(bpy.data.filepath)
    graph = bpy.context.evaluated_depsgraph_get()

    palette, meshes = [], []
    for empty in sorted(bpy.data.objects, key=lambda o: o.name):
        if empty.type == "EMPTY" and "moppe_mesh" in empty:
            meshes.append((empty["moppe_mesh"],
                           *export_mesh(empty, graph, palette)))
    points = sorted((o["moppe_point"], game(o.matrix_world.translation))
                    for o in bpy.data.objects
                    if o.type == "EMPTY" and "moppe_point" in o)

    guard = f"MOPPE_GAME_{stem.upper()}_HH"
    hh = [
        f"// Generated by tools/figure/export_model.py from models/{blend}.",
        "// Do not edit; edit the model and re-export.",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <moppe/game/model_mesh.hh>",
        "",
        f"namespace moppe::game::{stem} {{",
        "  // Assemblies, each in its own frame.",
    ]
    hh += [f"  extern const model_mesh::Mesh {name};"
           for name, _, _ in meshes]
    hh += ["", "  // Points in model space."]
    hh += [f"  extern const Vec3 {name};" for name, _ in points]
    hh += ["}", "", "#endif", ""]

    cc = [
        f"// Generated by tools/figure/export_model.py from models/{blend}.",
        "// Do not edit; edit the model and re-export.",
        "// clang-format off",
        "",
        f"#include <moppe/game/{stem}.hh>",
        "",
        f"namespace moppe::game::{stem} {{",
        "  namespace {",
        "    using model_mesh::Paint;",
        "    using model_mesh::Triangle;",
        "    using model_mesh::Vertex;",
        "",
        "    constexpr Paint paints[] = {",
    ]
    for name, colour, unlit in palette:
        cc.append(f"      {{{{{', '.join(f(x) for x in colour)}}}, "
                  f"{'true' if unlit else 'false'}}}, // {name}")
    cc.append("    };")
    for name, vertices, triangles in meshes:
        cc += ["", f"    constexpr Vertex {name}_vertices[] = {{"]
        cc += [f"      {{{triple(p)}, {triple(n)}}}," for p, n in vertices]
        cc += ["    };", f"    constexpr Triangle {name}_triangles[] = {{"]
        cc += [f"      {{{{{a}, {b}, {c}}}, {k}}},"
               for a, b, c, k in triangles]
        cc.append("    };")
    cc += ["  }", ""]
    for name, _, _ in meshes:
        cc.append(f"  const model_mesh::Mesh {name} {{{name}_vertices, "
                  f"{name}_triangles, paints}};")
    cc.append("")
    for name, p in points:
        cc.append(f"  const Vec3 {name} ({', '.join(f(x) for x in p)});")
    cc += ["}", ""]

    with open(out_hh, "w") as out:
        out.write("\n".join(hh))
    with open(out_cc, "w") as out:
        out.write("\n".join(cc))
    counts = ", ".join(f"{n} {len(t)}" for n, _, t in meshes)
    print(f"wrote {out_cc}: triangles {counts}; {len(points)} points")


main()
