"""Exports models/hiker.blend to moppe/game/figure_mesh.cc.

    Blender -b models/hiker.blend --python tools/figure/export.py

Writes the rest mesh in the game's frame (x right, y up, z forward): each
vertex with up to two bones and the first bone's weight, triangles with a
palette index, the palette as display colours, and each bone's rest frame
(origin and its local x, y = along the bone, z = roll reference). The game
skins by mapping every rest frame onto the frame it builds from the posed
skeleton; see game/figure.hh.
"""

import os

import bpy

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "moppe", "game", "figure_mesh.cc")

# The order of figure::Bone. Blender's .L is the figure's left, which is
# side -1 and index 0 of the skeleton's pairs.
BONES = [
    "pelvis", "spine", "chest", "head",
    "thigh.L", "thigh.R", "shin.L", "shin.R", "foot.L", "foot.R",
    "upper_arm.L", "upper_arm.R", "forearm.L", "forearm.R",
    "hand.L", "hand.R",
]


def game(v):
    return (v[0], v[2], -v[1])


def to_display(c):
    c = max(0.0, min(1.0, c))
    return c * 12.92 if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055


def f(x):
    s = f"{x:.5f}".rstrip("0")
    return (s + "0" if s.endswith(".") else s) + "f"


def triple(v):
    return "{" + ", ".join(f(x) for x in v) + "}"


def main():
    rig = bpy.data.objects["hiker_rig"]
    body = bpy.data.objects["hiker"]
    mesh = body.data
    to_rig = rig.matrix_world.inverted() @ body.matrix_world

    groups = {g.index: g.name for g in body.vertex_groups}
    vertices = []
    for v in mesh.vertices:
        weights = sorted(((g.weight, BONES.index(groups[g.group]))
                          for g in v.groups
                          if g.weight > 0 and groups[g.group] in BONES),
                         reverse=True)[:2]
        if not weights:
            raise SystemExit(f"vertex {v.index} has no bone")
        total = sum(w for w, _ in weights)
        first = weights[0][1]
        second = weights[1][1] if len(weights) > 1 else first
        vertices.append((game(to_rig @ v.co), first, second,
                         weights[0][0] / total))

    mesh.calc_loop_triangles()
    triangles = [(t.vertices[0], t.vertices[1], t.vertices[2],
                  t.material_index) for t in mesh.loop_triangles]

    colours = [tuple(to_display(c) for c in m.diffuse_color[:3])
               for m in mesh.materials]

    frames = []
    for name in BONES:
        m = rig.data.bones[name].matrix_local
        frames.append((game(m.col[3]), game(m.col[0]), game(m.col[1]),
                       game(m.col[2])))

    lines = [
        "// Generated by tools/figure/export.py from models/hiker.blend.",
        "// Do not edit; edit the model and re-export.",
        "",
        "#include <moppe/game/figure.hh>",
        "",
        "namespace moppe::game::figure {",
        "  namespace {",
        "    constexpr Frame rest_frames[] = {",
    ]
    for name, (o, x, y, z) in zip(BONES, frames):
        lines.append(f"      // {name}")
        lines.append(f"      {{{triple(o)},")
        lines.append(f"       {triple(x)},")
        lines.append(f"       {triple(y)},")
        lines.append(f"       {triple(z)}}},")
    lines += ["    };", "", "    constexpr DisplayColor palette[] = {"]
    for m, c in zip(mesh.materials, colours):
        lines.append(f"      {{{', '.join(f(x) for x in c)}}}, // {m.name}")
    lines += ["    };", "", "    constexpr Vertex rest_vertices[] = {"]
    for p, a, b, w in vertices:
        lines.append(f"      {{{triple(p)}, {{{a}, {b}}}, {f(w)}}},")
    lines += ["    };", "", "    constexpr Triangle mesh_triangles[] = {"]
    for a, b, c, m in triangles:
        lines.append(f"      {{{{{a}, {b}, {c}}}, {m}}},")
    lines += [
        "    };",
        "  }",
        "",
        "  const std::span<const Frame, bone_count> rest {rest_frames};",
        "  const std::span<const DisplayColor> colours {palette};",
        "  const std::span<const Vertex> vertices {rest_vertices};",
        "  const std::span<const Triangle> triangles {mesh_triangles};",
        "}",
        "",
    ]
    with open(OUT, "w") as out:
        out.write("\n".join(lines))
    print(f"wrote {OUT}: {len(vertices)} vertices, {len(triangles)} "
          f"triangles, {len(colours)} colours")


main()
