"""Exports models/hiker.blend to moppe/game/figure_mesh.cc.

    Blender -b models/hiker.blend --python tools/figure/export.py

Evaluates every mesh parented to the rig with its modifiers (subdivision,
bevels) in the rig's rest pose, and writes the merged result in the game's
frame (x right, y up, z forward): each vertex with its smooth normal and up
to four bone weights, triangles with a palette index, the palette as
display colours, and each bone's rest frame (origin and its local x, y =
along the bone, z = roll reference). The game skins by mapping every rest
frame onto the frame it builds from the posed skeleton; see game/figure.hh.
"""

import os

import bpy

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "moppe", "game", "figure_mesh.cc")

# The order of figure::Bone. Blender's .L is the figure's left, which is
# side -1 and index 0 of the skeleton's pairs.
BONES = [
    "pelvis", "spine", "chest", "head",
    "thigh.L", "thigh.R", "shin.L", "shin.R", "foot.L", "foot.R",
    "upper_arm.L", "upper_arm.R", "forearm.L", "forearm.R",
    "hand.L", "hand.R",
]
INFLUENCES = 4


def game(v):
    return (v[0], v[2], -v[1])


def to_display(c):
    c = max(0.0, min(1.0, c))
    return c * 12.92 if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055


def f(x):
    s = f"{x:.4f}".rstrip("0")
    s = s + "0" if s.endswith(".") else s
    return ("0.0" if s in ("-0.0", "0.0") else s) + "f"


def triple(v):
    return "{" + ", ".join(f(x) for x in v) + "}"


def main():
    rig = bpy.data.objects["hiker_rig"]
    rig.data.pose_position = "REST"
    graph = bpy.context.evaluated_depsgraph_get()
    graph.update()

    palette = []
    vertices = []
    triangles = []
    parts = sorted((o for o in rig.children if o.type == "MESH"),
                   key=lambda o: o.name)
    for obj in parts:
        evaluated = obj.evaluated_get(graph)
        mesh = evaluated.to_mesh()
        to_rig = rig.matrix_world.inverted() @ obj.matrix_world
        turn = to_rig.to_3x3()
        groups = {g.index: g.name for g in obj.vertex_groups}
        base = len(vertices)
        for v in mesh.vertices:
            weights = sorted(((g.weight, BONES.index(groups[g.group]))
                              for g in v.groups
                              if g.weight > 0 and g.group in groups and
                              groups[g.group] in BONES),
                             reverse=True)[:INFLUENCES]
            if not weights:
                raise SystemExit(f"{obj.name}: vertex {v.index} has no bone")
            total = sum(w for w, _ in weights)
            weights = [(w / total, b) for w, b in weights]
            while len(weights) < INFLUENCES:
                weights.append((0.0, weights[0][1]))
            normal = (turn @ v.normal).normalized()
            vertices.append((game(to_rig @ v.co), game(normal), weights))
        mesh.calc_loop_triangles()
        for t in mesh.loop_triangles:
            mat = mesh.materials[t.material_index]
            colour = tuple(to_display(c) for c in mat.diffuse_color[:3])
            if (mat.name, colour) not in palette:
                palette.append((mat.name, colour))
            triangles.append((base + t.vertices[0], base + t.vertices[1],
                              base + t.vertices[2],
                              palette.index((mat.name, colour))))
        evaluated.to_mesh_clear()
    rig.data.pose_position = "POSE"

    if len(vertices) > 65535:
        raise SystemExit(f"{len(vertices)} vertices overflow 16-bit indices")

    frames = []
    for name in BONES:
        m = rig.data.bones[name].matrix_local
        frames.append((game(m.col[3]), game(m.col[0]), game(m.col[1]),
                       game(m.col[2])))

    lines = [
        "// Generated by tools/figure/export.py from models/hiker.blend.",
        "// Do not edit; edit the model and re-export.",
        "// clang-format off",
        "",
        "#include <moppe/game/figure.hh>",
        "",
        "namespace moppe::game::figure {",
        "  namespace {",
        "    constexpr Frame rest_frames[] = {",
    ]
    for name, (o, x, y, z) in zip(BONES, frames):
        lines.append(f"      // {name}")
        lines.append(f"      {{{triple(o)}, {triple(x)},")
        lines.append(f"       {triple(y)}, {triple(z)}}},")
    lines += ["    };", "", "    constexpr DisplayColor palette[] = {"]
    for name, c in palette:
        lines.append(f"      {{{', '.join(f(x) for x in c)}}}, // {name}")
    lines += ["    };", "", "    constexpr Vertex rest_vertices[] = {"]
    for p, n, weights in vertices:
        bones = ", ".join(str(b) for _, b in weights)
        ws = ", ".join(f(w) for w, _ in weights)
        lines.append(f"      {{{triple(p)}, {triple(n)}, {{{bones}}}, "
                     f"{{{ws}}}}},")
    lines += ["    };", "", "    constexpr Triangle mesh_triangles[] = {"]
    for a, b, c, m in triangles:
        lines.append(f"      {{{{{a}, {b}, {c}}}, {m}}},")
    lines += [
        "    };",
        "  }",
        "",
        "  const std::span<const Frame, bone_count> rest {rest_frames};",
        "  const std::span<const DisplayColor> colours {palette};",
        "  const std::span<const Vertex> vertices {rest_vertices};",
        "  const std::span<const Triangle> triangles {mesh_triangles};",
        "}",
        "",
    ]
    with open(OUT, "w") as out:
        out.write("\n".join(lines))
    print(f"wrote {OUT}: {len(parts)} parts, {len(vertices)} vertices, "
          f"{len(triangles)} triangles, {len(palette)} colours")


main()
