// Generated by tools/figure/export_model.py from models/bike.blend.
// Do not edit; edit the model and re-export.

#ifndef MOPPE_GAME_BIKE_MODEL_HH
#define MOPPE_GAME_BIKE_MODEL_HH

#include <moppe/game/model_mesh.hh>

namespace moppe::game::bike_model {
  // Assemblies, each in its own frame.
  extern const model_mesh::Mesh chassis;
  extern const model_mesh::Mesh fork_sliders;
  extern const model_mesh::Mesh nozzle;
  extern const model_mesh::Mesh shock_body;
  extern const model_mesh::Mesh shock_shaft;
  extern const model_mesh::Mesh steering;
  extern const model_mesh::Mesh swingarm;
  extern const model_mesh::Mesh wheel;

  // Points in model space.
  extern const Vec3 fork_top;
  extern const Vec3 front_axle;
  extern const Vec3 grip_left;
  extern const Vec3 grip_right;
  extern const Vec3 headlight;
  extern const Vec3 muffler_tip;
  extern const Vec3 nozzle_left;
  extern const Vec3 nozzle_right;
  extern const Vec3 peg_left;
  extern const Vec3 peg_right;
  extern const Vec3 rear_axle;
  extern const Vec3 saddle;
  extern const Vec3 shock_bottom;
  extern const Vec3 shock_top;
  extern const Vec3 steering_head;
  extern const Vec3 swingarm_pivot;
}

#endif
