// Generated by tools/figure/export_model.py from models/glider.blend.
// Do not edit; edit the model and re-export.

#ifndef MOPPE_GAME_GLIDER_MODEL_HH
#define MOPPE_GAME_GLIDER_MODEL_HH

#include <moppe/game/model_mesh.hh>

namespace moppe::game::glider_model {
  // Assemblies, each in its own frame.
  extern const model_mesh::Mesh glider;
  extern const model_mesh::Mesh tether;

  // Points in model space.
  extern const Vec3 grip_left;
  extern const Vec3 grip_right;
  extern const Vec3 harness;
}

#endif
