#include <moppe/nhal/demo/scene.hh>

// Generated by luv-shaderc from shaders/scene.lisp.
#include <forest_wind.hh>
#include <resolve.hh>
#include <sky.hh>
#include <terrain.hh>
#include <terrain_shadow.hh>
#include <tonemap.hh>
#include <trees.hh>
#include <trees_shadow.hh>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <vector>

namespace moppe::nhal::demo {
  // Every program but the tonemap reads the same frame block.
  using FrameState = shaders::terrain::FrameState;
  static_assert (sizeof (FrameState) == sizeof (shaders::trees::FrameState));
  static_assert (sizeof (FrameState) == sizeof (shaders::sky::FrameState));

  namespace {
    constexpr float pi = 3.14159265358979f;
    constexpr std::uint32_t grid = 257;
    constexpr float cell = 4.0f;
    constexpr std::uint32_t samples = 4; // scene multisampling
    constexpr std::uint32_t shadow_size = 4096;

    struct Vec3 {
      float x = 0, y = 0, z = 0;
      Vec3 operator+ (Vec3 o) const { return { x + o.x, y + o.y, z + o.z }; }
      Vec3 operator- (Vec3 o) const { return { x - o.x, y - o.y, z - o.z }; }
      Vec3 operator* (float s) const { return { x * s, y * s, z * s }; }
    };

    float dot (Vec3 a, Vec3 b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
    Vec3 cross (Vec3 a, Vec3 b) {
      return { a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z,
               a.x * b.y - a.y * b.x };
    }
    Vec3 normalize (Vec3 v) { return v * (1.0f / std::sqrt (dot (v, v))); }
    std::array<float, 4> lanes (Vec3 v, float w) { return { v.x, v.y, v.z, w }; }

    float hash (int x, int z) {
      std::uint32_t h = std::uint32_t (x) * 374761393u
                        + std::uint32_t (z) * 668265263u;
      h = (h ^ (h >> 13)) * 1274126177u;
      return float ((h ^ (h >> 16)) & 0xffffff) / float (0x1000000);
    }

    float value_noise (float x, float z) {
      const int ix = int (std::floor (x)), iz = int (std::floor (z));
      float fx = x - ix, fz = z - iz;
      fx = fx * fx * (3 - 2 * fx);
      fz = fz * fz * (3 - 2 * fz);
      const float a = hash (ix, iz), b = hash (ix + 1, iz);
      const float c = hash (ix, iz + 1), d = hash (ix + 1, iz + 1);
      return (a + (b - a) * fx) + ((c + (d - c) * fx) - (a + (b - a) * fx)) * fz;
    }

    float fbm (float x, float z) {
      float sum = 0, amplitude = 0.5f;
      for (int octave = 0; octave < 6; ++octave) {
        sum += amplitude * value_noise (x, z);
        x = x * 2.03f + 17.1f;
        z = z * 2.03f - 9.7f;
        amplitude *= 0.5f;
      }
      return sum;
    }

    // A valley: noise ridges rising away from the middle of the map.
    float height_at (float x, float z) {
      const float span = (grid - 1) * cell;
      const float dx = x / span - 0.5f, dz = z / span - 0.5f;
      const float rim = dx * dx + dz * dz;
      return 170.0f * std::pow (fbm (x / 330.0f, z / 330.0f), 1.4f)
             + 260.0f * rim;
    }

    struct Rng {
      std::uint32_t state = 0x9e3779b9u;
      float next () {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        return float (state & 0xffffff) / float (0x1000000);
      }
    };

    // The Halton sequence's radical inverse: well-spread jitter offsets.
    float halton (std::uint32_t index, std::uint32_t base) {
      float fraction = 1, result = 0;
      while (index > 0) {
        fraction /= float (base);
        result += fraction * float (index % base);
        index /= base;
      }
      return result;
    }

    template <typename T>
    std::span<const std::byte> bytes (const std::vector<T>& values) {
      return std::as_bytes (std::span (values));
    }

  }

  Scene::Scene (Device& device, const Shaders& shaders, float render_scale)
    : m_device (device), m_grid (grid), m_cell (cell),
      m_render_scale (render_scale) {
    // Terrain samples: height and normal per grid point.
    std::vector<float> heights (grid * grid);
    for (std::uint32_t z = 0; z < grid; ++z)
      for (std::uint32_t x = 0; x < grid; ++x)
        heights[z * grid + x] = height_at (x * cell, z * cell);
    auto h = [&] (int x, int z) {
      x = std::clamp (x, 0, int (grid) - 1);
      z = std::clamp (z, 0, int (grid) - 1);
      return heights[z * grid + x];
    };
    std::vector<std::array<float, 4>> terrain (grid * grid);
    for (int z = 0; z < int (grid); ++z)
      for (int x = 0; x < int (grid); ++x) {
        const Vec3 n = normalize ({ h (x - 1, z) - h (x + 1, z), 2 * cell,
                                    h (x, z - 1) - h (x, z + 1) });
        terrain[z * grid + x] = { h (x, z), n.x, n.y, n.z };
      }
    std::vector<std::uint32_t> indices;
    for (std::uint32_t z = 0; z + 1 < grid; ++z)
      for (std::uint32_t x = 0; x + 1 < grid; ++x) {
        const std::uint32_t a = z * grid + x, b = a + 1, c = a + grid,
                            d = c + 1;
        indices.insert (indices.end (), { a, c, b, b, c, d });
      }
    m_terrain_index_count = std::uint32_t (indices.size ());
    m_terrain_samples = device.create_buffer (
      { .size = terrain.size () * 16, .label = "terrain samples" },
      bytes (terrain));
    m_terrain_indices = device.create_buffer (
      { .size = indices.size () * 4, .label = "terrain indices" },
      bytes (indices));

    // A spruce stand on the gentler mid slopes, thinned by a density field.
    float highest = 0;
    for (float value : heights)
      highest = std::max (highest, value);
    std::vector<std::array<float, 4>> trees;
    Rng rng;
    const float span = (grid - 1) * cell;
    for (int attempt = 0; attempt < 60000 && trees.size () < 2 * 9000;
         ++attempt) {
      const float x = rng.next () * span, z = rng.next () * span;
      const int gx = int (x / cell), gz = int (z / cell);
      const auto& sample = terrain[gz * grid + gx];
      const float y = sample[0];
      const float density = fbm (x / 140.0f + 40, z / 140.0f - 13);
      if (sample[2] < 0.82f || y > highest * 0.62f || density < 0.47f)
        continue;
      const float tall = 14.0f + 13.0f * rng.next ();
      trees.push_back ({ x, y, z, tall });
      trees.push_back ({ tall * 0.017f, tall * (0.19f + 0.05f * rng.next ()),
                         0.22f + 0.1f * rng.next (), rng.next () });
    }
    m_tree_count = std::uint32_t (trees.size () / 2);
    m_tree_instances = device.create_buffer (
      { .size = trees.size () * 16, .label = "tree instances" },
      bytes (trees));
    m_tree_animated = device.create_buffer (
      { .size = std::uint64_t (m_tree_count) * 3 * 16,
        .usage = buffer_storage_write, .label = "swaying trees" });
    m_tree_draw = device.create_buffer (
      { .size = sizeof (DrawIndexedIndirectArgs),
        .usage = buffer_storage_write | buffer_indirect,
        .label = "visible tree draw" });
    m_tree_shadow_draw = device.create_buffer (
      { .size = sizeof (DrawIndexedIndirectArgs),
        .usage = buffer_storage_write | buffer_indirect,
        .label = "shadow tree draw" });
    m_tree_visible = device.create_buffer (
      { .size = std::uint64_t (m_tree_count) * 4,
        .usage = buffer_storage_write, .label = "visible trees" });

    // One spruce: an 8-facet trunk and three crown tiers, 48 vertices made
    // by the vertex shader from its index.
    std::vector<std::uint16_t> tree;
    for (std::uint16_t f = 0; f < 8; ++f) {
      const std::uint16_t a = f, b = f + 1, c = 9 + f, d = 10 + f;
      tree.insert (tree.end (), { a, b, c, b, d, c });
    }
    for (std::uint16_t tier = 0; tier < 3; ++tier) {
      const std::uint16_t base = 18 + tier * 10, apex = base + 9;
      for (std::uint16_t f = 0; f < 8; ++f)
        tree.insert (tree.end (), { std::uint16_t (base + f),
                                    std::uint16_t (base + f + 1), apex });
    }
    m_tree_index_count = std::uint32_t (tree.size ());
    m_tree_indices = device.create_buffer (
      { .size = tree.size () * 2, .label = "tree indices" }, bytes (tree));

    // Pipelines: the scene draws RGBA16F over reversed-Z depth, 4x
    // multisampled natively or single-sampled for the temporal resolve; the
    // tonemap writes the drawable.
    for (int mode = 0; mode < 2; ++mode) {
      // Colour and screen motion, which the temporal resolve follows.
      RenderPipelineDesc desc;
      desc.color_formats[0] = Format::rgba16_float;
      desc.color_formats[1] = Format::rg16_float;
      desc.color_count = 2;
      desc.depth_format = Format::d32_float;
      desc.samples = mode == 0 ? samples : 1;
      desc.program = &shaders::terrain::program;
      desc.vertex = shaders.terrain_vertex;
      desc.fragment = shaders.terrain_fragment;
      m_terrain[mode] = device.create_render_pipeline (desc);

      desc.program = &shaders::trees::program;
      desc.vertex = shaders.trees_vertex;
      desc.fragment = shaders.trees_fragment;
      m_trees[mode] = device.create_render_pipeline (desc);

      // The sky fills only what nothing nearer covered: it sits at the far
      // plane, which reversed-Z clears to zero.
      desc.program = &shaders::sky::program;
      desc.vertex = shaders.sky_vertex;
      desc.fragment = shaders.sky_fragment;
      desc.depth_write = false;
      m_sky[mode] = device.create_render_pipeline (desc);
    }

    RenderPipelineDesc resolve;
    resolve.program = &shaders::resolve::program;
    resolve.vertex = shaders.resolve_vertex;
    resolve.fragment = shaders.resolve_fragment;
    resolve.color_formats[0] = Format::rgba16_float;
    m_resolve = device.create_render_pipeline (resolve);

    RenderPipelineDesc tonemap;
    tonemap.program = &shaders::tonemap::program;
    tonemap.vertex = shaders.tonemap_vertex;
    tonemap.fragment = shaders.tonemap_fragment;
    tonemap.color_formats[0] = device.surface_format ();
    m_tonemap = device.create_render_pipeline (tonemap);

    // The sun's view: depth only, conventional Z, biased away from the sun.
    RenderPipelineDesc caster;
    caster.color_count = 0;
    caster.depth_format = Format::d32_float;
    caster.depth_compare = CompareOp::less_equal;
    caster.depth_bias = 2;
    caster.slope_scaled_depth_bias = 2.0f;
    caster.program = &shaders::terrain_shadow::program;
    caster.vertex = shaders.terrain_shadow_vertex;
    m_terrain_shadow = device.create_render_pipeline (caster);
    caster.program = &shaders::trees_shadow::program;
    caster.vertex = shaders.trees_shadow_vertex;
    m_trees_shadow = device.create_render_pipeline (caster);
    m_shadow_map = device.create_texture ({ shadow_size, shadow_size,
                                            Format::d32_float,
                                            usage_depth | usage_sampled, 1,
                                            "sun shadow" });

    m_wind = device.create_compute_pipeline (
      { &shaders::forest_wind::program, shaders.forest_wind_compute,
        "forest wind" });
  }

  Scene::~Scene () {
    m_device.wait_idle ();
    for (Texture t : { m_color, m_motion, m_depth, m_scene, m_low_color,
                       m_low_motion, m_low_depth, m_history[0], m_history[1],
                       m_shadow_map })
      if (t)
        m_device.destroy (t);
    for (Buffer b : { m_terrain_samples, m_terrain_indices, m_tree_instances,
                      m_tree_indices, m_tree_animated, m_tree_draw,
                      m_tree_shadow_draw, m_tree_visible })
      m_device.destroy (b);
    for (Pipeline p : { m_terrain[0], m_terrain[1], m_trees[0], m_trees[1],
                        m_sky[0], m_sky[1], m_tonemap, m_wind, m_resolve,
                        m_terrain_shadow, m_trees_shadow })
      m_device.destroy (p);
  }

  void Scene::set_temporal (bool temporal) {
    if (temporal != m_temporal)
      m_restart = true;
    m_temporal = temporal;
  }

  void Scene::make_targets () {
    for (Texture t : { m_color, m_motion, m_depth, m_scene, m_low_color,
                       m_low_motion, m_low_depth, m_history[0], m_history[1] })
      if (t)
        m_device.destroy (t);
    m_width = m_device.surface_width ();
    m_height = m_device.surface_height ();
    m_low_width = std::max (1u, std::uint32_t (m_width * m_render_scale));
    m_low_height = std::max (1u, std::uint32_t (m_height * m_render_scale));
    m_low_color = m_device.create_texture ({ m_low_width, m_low_height,
                                             Format::rgba16_float,
                                             usage_render_target
                                               | usage_sampled,
                                             1, "jittered scene" });
    m_low_motion = m_device.create_texture ({ m_low_width, m_low_height,
                                              Format::rg16_float,
                                              usage_render_target
                                                | usage_sampled,
                                              1, "jittered motion" });
    m_low_depth = m_device.create_texture ({ m_low_width, m_low_height,
                                             Format::d32_float,
                                             usage_depth | usage_sampled, 1,
                                             "jittered depth" });
    for (int i = 0; i < 2; ++i)
      m_history[i] = m_device.create_texture (
        { m_width, m_height, Format::rgba16_float,
          usage_render_target | usage_sampled, 1, "temporal history" });
    m_restart = true;
    m_color = m_device.create_texture ({ m_width, m_height,
                                         Format::rgba16_float,
                                         usage_render_target, samples,
                                         "scene samples" });
    m_motion = m_device.create_texture ({ m_width, m_height,
                                          Format::rg16_float,
                                          usage_render_target, samples,
                                          "scene motion" });
    m_depth = m_device.create_texture ({ m_width, m_height, Format::d32_float,
                                         usage_depth, samples,
                                         "scene depth" });
    m_scene = m_device.create_texture ({ m_width, m_height,
                                         Format::rgba16_float,
                                         usage_render_target | usage_sampled,
                                         1, "scene" });
  }

  void Scene::fly (const Flight& input, double seconds) {
    const bool moved = input.forward || input.strafe || input.rise
                       || input.turn || input.pitch;
    if (!m_flying && !moved)
      return;
    m_flying = true;
    const float dt = float (seconds);
    m_yaw += input.turn * 1.6f * dt;
    m_pitch = std::clamp (m_pitch + input.pitch * 1.2f * dt, -1.4f, 1.4f);
    const Vec3 ahead { std::cos (m_yaw), 0, std::sin (m_yaw) };
    const Vec3 side { -ahead.z, 0, ahead.x };
    const float speed = (input.boost ? 120.0f : 30.0f) * dt;
    Vec3 eye = Vec3 { m_eye[0], m_eye[1], m_eye[2] }
               + ahead * (input.forward * speed)
               + side * (input.strafe * speed)
               + Vec3 { 0, input.rise * speed, 0 };
    const float span = (m_grid - 1) * m_cell;
    eye.x = std::clamp (eye.x, 0.0f, span);
    eye.z = std::clamp (eye.z, 0.0f, span);
    eye.y = std::max (eye.y, height_at (eye.x, eye.z) + 1.7f);
    m_eye[0] = eye.x, m_eye[1] = eye.y, m_eye[2] = eye.z;
  }

  bool Scene::render (double seconds) {
    if (!m_device.begin_frame ())
      return false;
    if (m_width != m_device.surface_width ()
        || m_height != m_device.surface_height ())
      make_targets ();

    // A slow orbit around the valley, looking across it, until flown.
    const float span = (m_grid - 1) * m_cell;
    Vec3 eye, forward;
    if (m_flying) {
      eye = { m_eye[0], m_eye[1], m_eye[2] };
      forward = { std::cos (m_pitch) * std::cos (m_yaw), std::sin (m_pitch),
                  std::cos (m_pitch) * std::sin (m_yaw) };
    } else {
      const Vec3 centre { span * 0.5f, 0, span * 0.5f };
      const float angle = float (seconds) * 0.04f;
      eye = centre + Vec3 { std::cos (angle), 0, std::sin (angle) } * 300;
      eye.y = height_at (eye.x, eye.z) + 42;
      Vec3 target = centre
                    + Vec3 { std::cos (angle + 2.2f), 0,
                             std::sin (angle + 2.2f) } * 180;
      target.y = height_at (target.x, target.z) + 20;
      forward = normalize (target - eye);
      m_eye[0] = eye.x, m_eye[1] = eye.y, m_eye[2] = eye.z;
      m_yaw = std::atan2 (forward.z, forward.x);
      m_pitch = std::asin (forward.y);
    }
    const Vec3 right = normalize (cross (forward, { 0, 1, 0 }));
    const Vec3 up = cross (right, forward);
    const float tan_y = std::tan (27.0f * pi / 180.0f);
    const float tan_x = tan_y * float (m_width) / float (m_height);

    FrameState frame;
    frame.camera_position = lanes (eye, float (seconds));
    frame.camera_right = lanes (right * (1 / tan_x), tan_x);
    frame.camera_up = lanes (up * (1 / tan_y), tan_y);
    frame.camera_forward = lanes (forward, 0.5f);
    frame.sun_direction = lanes (normalize ({ 0.55f, 0.32f, 0.35f }), 0);
    frame.sun_color = { 3.2f, 2.75f, 2.2f, 0 };
    frame.sky_zenith = { 0.22f, 0.36f, 0.66f, 0 };
    frame.sky_horizon = { 0.66f, 0.70f, 0.74f, 0.0011f };
    frame.terrain = { m_cell, float (m_grid), 0, 0 };
    frame.forest = { float (m_tree_index_count), float (m_tree_count), 1.0f,
                     0 };

    // The frustum's planes as (normal, offset), normals pointing inward:
    // each side leans from the view direction by the half-angle's tangent.
    auto plane = [&] (Vec3 normal) {
      normal = normalize (normal);
      return lanes (normal, -dot (normal, eye));
    };
    frame.frustum_left = plane (right + forward * tan_x);
    frame.frustum_right = plane (right * -1.0f + forward * tan_x);
    frame.frustum_top = plane (up * -1.0f + forward * tan_y);
    frame.frustum_bottom = plane (up + forward * tan_y);
    frame.frustum_near = lanes (forward, -dot (forward, eye) - 0.5f);

    // An orthographic sun over the whole map: light x and y span -1..1,
    // depth runs 0..1 away from the sun through the map's bounding sphere.
    {
      const Vec3 sun = normalize ({ frame.sun_direction[0],
                                    frame.sun_direction[1],
                                    frame.sun_direction[2] });
      const Vec3 away = sun * -1.0f;
      const Vec3 across = normalize (cross (away, { 0, 1, 0 }));
      const Vec3 rise = cross (across, away);
      const Vec3 middle { span * 0.5f, 120.0f, span * 0.5f };
      const float reach = span * 0.75f;
      auto row = [&] (Vec3 axis, float scale, float offset) {
        return lanes (axis * scale, offset - dot (axis, middle) * scale);
      };
      frame.shadow_row_x = row (across, 1 / reach, 0);
      frame.shadow_row_y = row (rise, 1 / reach, 0);
      frame.shadow_row_z = row (away, 0.5f / reach, 0.5f);
      frame.shadow = { 1.0f / shadow_size, 0.0004f, 0, 0 };
    }
    // Temporal upscaling: a Halton jitter of up to half a scene pixel, and
    // last frame's camera for reprojection.
    const std::array<std::array<float, 4>, 4> camera {
      frame.camera_position, frame.camera_right, frame.camera_up,
      frame.camera_forward };
    if (m_restart)
      m_previous = camera;
    frame.previous_position = m_previous[0];
    frame.previous_right = m_previous[1];
    frame.previous_up = m_previous[2];
    frame.previous_forward = m_previous[3];
    const std::uint32_t phase = m_frame++ % 16 + 1;
    const float jitter_x = m_temporal ? (halton (phase, 2) - 0.5f) * 2
                                          / float (m_low_width)
                                      : 0.0f;
    const float jitter_y = m_temporal ? (halton (phase, 3) - 0.5f) * 2
                                          / float (m_low_height)
                                      : 0.0f;
    frame.temporal = { float (m_low_width), float (m_low_height), jitter_x,
                       jitter_y };
    frame.temporal_blend = { m_restart ? 1.0f : 0.1f, 0, float (m_width),
                             float (m_height) };
    m_previous = camera;
    m_restart = false;

    const Transient uniforms = m_device.allocate (sizeof frame);
    std::memcpy (uniforms.data, &frame, sizeof frame);

    // The wind counts the visible trees into the draw's instance count.
    const std::uint32_t none = 0;
    m_device.copy_to_buffer (
      m_tree_draw, offsetof (DrawIndexedIndirectArgs, instance_count),
      m_device.upload (std::span (&none, 1)));
    m_device.begin_compute_pass ("wind and culling");
    m_device.set_pipeline (m_wind);
    m_device.set_buffer (0, uniforms);
    m_device.set_buffer (1, m_tree_instances);
    m_device.set_buffer (2, m_tree_animated);
    m_device.set_buffer (3, m_tree_draw);
    m_device.set_buffer (4, m_tree_shadow_draw);
    m_device.set_buffer (5, m_tree_visible);
    m_device.dispatch ((m_tree_count + 63) / 64);
    m_device.end_compute_pass ();

    RenderPassDesc shadow;
    shadow.label = "sun shadow";
    shadow.depth = { m_shadow_map, Load::clear, Store::store, 1.0f };
    m_device.begin_render_pass (shadow);
    m_device.set_buffer (0, uniforms);
    m_device.set_pipeline (m_terrain_shadow);
    m_device.set_buffer (1, m_terrain_samples);
    m_device.draw_indexed (m_terrain_indices, IndexType::uint32,
                           m_terrain_index_count);
    m_device.set_pipeline (m_trees_shadow);
    m_device.set_buffer (1, m_tree_animated);
    m_device.draw_indexed_indirect (m_tree_indices, IndexType::uint16,
                                    m_tree_shadow_draw);
    m_device.end_render_pass ();

    const int mode = m_temporal ? 1 : 0;
    RenderPassDesc pass;
    pass.label = m_temporal ? "jittered scene" : "scene, 4x MSAA";
    pass.color_count = 2;
    if (m_temporal) {
      pass.colors[0] = { m_low_color, Load::clear, Store::store,
                         { 0, 0, 0, 1 } };
      pass.colors[1] = { m_low_motion, Load::clear, Store::store,
                         { 0, 0, 0, 0 } };
      pass.depth = { m_low_depth, Load::clear, Store::store, 0.0f };
    } else {
      pass.colors[0] = { m_color, Load::clear, Store::discard,
                         { 0, 0, 0, 1 }, m_scene };
      pass.colors[1] = { m_motion, Load::clear, Store::discard,
                         { 0, 0, 0, 0 } };
      pass.depth = { m_depth, Load::clear, Store::discard, 0.0f };
    }
    m_device.begin_render_pass (pass);
    m_device.set_buffer (0, uniforms);
    m_device.set_texture (0, m_shadow_map);

    m_device.set_pipeline (m_terrain[mode]);
    m_device.set_buffer (1, m_terrain_samples);
    m_device.draw_indexed (m_terrain_indices, IndexType::uint32,
                           m_terrain_index_count);

    m_device.set_pipeline (m_trees[mode]);
    m_device.set_buffer (1, m_tree_animated);
    m_device.set_buffer (2, m_tree_visible);
    m_device.draw_indexed_indirect (m_tree_indices, IndexType::uint16,
                                    m_tree_draw);

    m_device.set_pipeline (m_sky[mode]);
    m_device.draw (3);
    m_device.end_render_pass ();

    // The temporal resolve: this frame into the history it reads last
    // frame's from.
    Texture image = m_scene;
    if (m_temporal) {
      Texture& previous = m_history[m_frame % 2];
      Texture& next = m_history[(m_frame + 1) % 2];
      RenderPassDesc resolve;
      resolve.label = "temporal resolve";
      resolve.color_count = 1;
      resolve.colors[0] = { next, Load::discard, Store::store };
      m_device.begin_render_pass (resolve);
      m_device.set_pipeline (m_resolve);
      m_device.set_buffer (0, uniforms);
      m_device.set_texture (0, m_low_color);
      m_device.set_texture (1, m_low_motion);
      m_device.set_texture (2, m_low_depth);
      m_device.set_texture (3, previous);
      m_device.draw (3);
      m_device.end_render_pass ();
      image = next;
    }

    RenderPassDesc present;
    present.label = "tonemap";
    present.color_count = 1;
    present.colors[0] = { m_device.backbuffer (), Load::discard,
                          Store::store };
    m_device.begin_render_pass (present);
    m_device.set_pipeline (m_tonemap);
    m_device.set_buffer (0, uniforms);
    m_device.set_texture (0, image);
    m_device.draw (3);
    m_device.end_render_pass ();
    return true;
  }
}
