# -*- python -*-

Import('env')

env.Library('../moppe-gfx', ['camera.cc',
                             'mouse.cc',
                             'terrain.cc',
                             'vertex-array.cc',
                             'shader.cc',
                             'texture.cc',
                             'tga.cc',
                             'sky.cc'])

