# -*- python -*-

import sys

env = Environment(CXX     = 'g++',
                  CCFLAGS = ['-g', '-DDEBUG=1', '-Wall'],
                  CPPPATH = ['#/', '#/vendor/boost', '#/vendor/include'],
                  LIBPATH = ['#/build', '#/vendor/lib'])

if sys.platform == 'darwin':
    env.AppendUnique(CPPPATH =
                     ['/System/Library/Frameworks/OpenGL.framework/Headers',
                      '/System/Library/Frameworks/GLUT.framework/Headers',
                      '#/vendor/glew/include'],
                     FRAMEWORKS = ['OpenGL', 'GLUT'],
                     CCFLAGS = ['-DMAC'])

Export('env')

env.SConscript(['map/SConscript',
                'app/SConscript',
                'gfx/SConscript',
                'mov/SConscript'])
