# -*- python -*-

import sys

env = Environment(CXX     = 'g++',
                  CCFLAGS = ['-g', '-DDEBUG=1'],
                  CPPPATH = ['#/',
                             '#/vendor/boost'])

if sys.platform == 'darwin':
    env.AppendUnique(CPPPATH =
                     ['/System/Library/Frameworks/OpenGL.framework/Headers',
                      '/System/Library/Frameworks/GLUT.framework/Headers'],
                     FRAMEWORKS = ['OpenGL', 'GLUT'],
                     CCFLAGS = ['-DMAC'])

Export('env')

env.SConscript(['map/SConscript',
                'app/SConscript',
                'gfx/SConscript'])
