# -*- python -*-

Import('env')

CF_NAME = 'MScript'

BNFC_FILES = ['Abs.hs', 'Lex.x', 'Par.y', 'Doc.tex', 'Skel.hs',
              'Print.hs', 'Test.hs', 'ErrM.hs']

env.Command([CF_NAME + '/' + x for x in BNFC_FILES],
            CF_NAME + '.cf',
            "cd ${SOURCE.dir} && bnfc -d ${SOURCE.file}")

env.Command(CF_NAME + '/Lex.hs',
            CF_NAME + '/Lex.x',
            "alex -g $SOURCE")

env.Command([CF_NAME + '/Par.hs', CF_NAME + '/Par.info'],
            CF_NAME + '/Par.y',
            "happy --debug --info --ghc --coerce --array $SOURCE")

check = env.Command('check', 'Main.hs',
                    "ghc -o check --make $SOURCE -i:moppe/script/compiler")
Depends(check, 'MScript.cf')
